"""Configuracion y constantes compartidas por toda la aplicacion."""
from pathlib import Path
import os
from dotenv import load_dotenv

# Cargar variables de entorno desde .env si existe
env_path = Path(__file__).resolve().parent.parent / '.env'
if env_path.exists():
    load_dotenv(env_path)

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
DATA_DIR.mkdir(exist_ok=True)
DB_PATH = DATA_DIR / "stock.db"
CLAVES_PATH = DATA_DIR / "secret.json"

# Directorio de logs de la aplicacion (montado como volumen en docker-compose.yml
# para que sobrevivan a la reconstruccion del contenedor). El Panel de Gestion
# del Servidor (proyecto independiente) lee de aqui para mostrar los logs en vivo.
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)
LOG_FILE_PATH = LOGS_DIR / "stockhogar.log"

DIAS_AVISO_DEFECTO = 30

# Duracion de la sesion iniciada: al ser un dispositivo domestico compartido,
# el login es persistente para no tener que volver a autenticarse cada vez.
DIAS_SESION = 365

# La cookie de sesion solo se marca "Secure" (exigir HTTPS) si APP_URL usa https.
# En local (http://localhost) se deja sin marcar para poder seguir probando sin TLS.
USAR_COOKIE_SEGURA = os.getenv("APP_URL", "http://localhost:5000").startswith("https://")

# Categorias de partida (se insertan una sola vez; a partir de ahi son
# totalmente editables desde la app). "Otros" es el comodin de respaldo y
# no se puede borrar. Se mantienen las 5 originales (por compatibilidad con
# productos ya creados con ellas) y se añaden las secciones habituales de
# un supermercado español, para que el catálogo de productos quede bien
# organizado.
CATEGORIAS_DEFECTO = [
    ("Alimentación", "🍎"),
    ("Limpieza", "🧴"),
    ("Higiene", "🧼"),
    ("Bebidas", "🥤"),
    ("Otros", "🗂️"),
    ("Frutas y Verduras", "🥕"),
    ("Panadería y Bollería", "🥖"),
    ("Lácteos y Huevos", "🥚"),
    ("Carnes y Embutidos", "🥩"),
    ("Pescados y Mariscos", "🐟"),
    ("Congelados", "🧊"),
    ("Despensa", "🥫"),
    ("Cereales y Pasta", "🍝"),
    ("Snacks y Dulces", "🍫"),
    ("Bebé", "🍼"),
    ("Mascotas", "🐶"),
    ("Hogar", "🏠"),
    ("Farmacia y Botiquín", "💊"),
    ("Bazar", "🎁"),
    ("Ferretería", "🔧"),
    ("Alternativas Vegetales", "🌱"),
    ("Papelería y Oficina", "pencil-ruler"),
    ("Jardín y Terraza", "sprout"),
    ("Automóvil", "car-front"),
]
CATEGORIA_DEFECTO = "Otros"

# Catalogo de productos habituales de supermercado en España (investigado:
# leche, huevos, pan, aceite, pasta, arroz, frutas y verduras son los
# alimentos que compra la inmensa mayoria de hogares). Se siembra una vez en
# el historial de articulos como sugerencias listas para usar; el usuario
# puede editarlas, borrarlas o añadir las suyas sin límite.
# Formato: (nombre, categoria, icono, unidad, sub_descripcion)
CATALOGO_DEFECTO = [
    # Frutas y Verduras
    ("Plátanos", "Frutas y Verduras", "🍌", "kg", None),
    ("Manzanas", "Frutas y Verduras", "🍎", "kg", None),
    ("Naranjas", "Frutas y Verduras", "🍊", "kg", None),
    ("Limones", "Frutas y Verduras", "🍋", "kg", None),
    ("Fresas", "Frutas y Verduras", "🍓", "kg", None),
    ("Uvas", "Frutas y Verduras", "🍇", "kg", None),
    ("Aguacates", "Frutas y Verduras", "🥑", "ud", None),
    ("Tomates", "Frutas y Verduras", "🍅", "kg", None),
    ("Lechuga", "Frutas y Verduras", "🥬", "ud", None),
    ("Cebollas", "Frutas y Verduras", "🧅", "kg", None),
    ("Ajos", "Frutas y Verduras", "🧄", "ud", None),
    ("Patatas", "Frutas y Verduras", "🥔", "kg", None),
    ("Pimientos", "Frutas y Verduras", "🌶️", "kg", None),
    ("Zanahorias", "Frutas y Verduras", "🥕", "kg", None),
    ("Pepino", "Frutas y Verduras", "🥒", "ud", None),
    ("Brócoli", "Frutas y Verduras", "🥦", "ud", None),
    ("Champiñones", "Frutas y Verduras", "🍄", "kg", None),
    ("Calabacín", "Frutas y Verduras", "🥒", "kg", None),
    ("Berenjena", "Frutas y Verduras", "🍆", "kg", None),
    ("Espinacas", "Frutas y Verduras", "🥬", "ud", None),
    ("Peras", "Frutas y Verduras", "🍐", "kg", None),
    ("Melocotones", "Frutas y Verduras", "🍑", "kg", None),
    ("Sandía", "Frutas y Verduras", "🍉", "ud", None),
    ("Melón", "Frutas y Verduras", "🍈", "ud", None),
    ("Piña", "Frutas y Verduras", "🍍", "ud", None),
    ("Kiwis", "Frutas y Verduras", "🥝", "kg", None),
    ("Coliflor", "Frutas y Verduras", "🥦", "ud", None),
    ("Calabaza", "Frutas y Verduras", "🎃", "kg", None),
    ("Puerros", "Frutas y Verduras", "🥬", "ud", None),
    ("Apio", "Frutas y Verduras", "🥬", "ud", None),
    ("Mandarinas", "Frutas y Verduras", "🍊", "kg", None),
    ("Cerezas", "Frutas y Verduras", "🍒", "kg", None),
    ("Ciruelas", "Frutas y Verduras", "🍑", "kg", None),
    ("Granada", "Frutas y Verduras", "🌰", "ud", None),
    ("Higos", "Frutas y Verduras", "🌰", "kg", None),
    ("Judías verdes", "Frutas y Verduras", "🫛", "kg", None),
    ("Espárragos", "Frutas y Verduras", "🌱", "ud", None),
    ("Alcachofas", "Frutas y Verduras", "🌱", "kg", None),
    ("Rábanos", "Frutas y Verduras", "🥕", "ud", None),
    ("Remolacha", "Frutas y Verduras", "🥕", "kg", None),
    # Panadería y Bollería
    ("Pan de barra", "Panadería y Bollería", "🥖", "ud", None),
    ("Pan de molde", "Panadería y Bollería", "🍞", "ud", None),
    ("Croissants", "Panadería y Bollería", "🥐", "ud", None),
    ("Magdalenas", "Panadería y Bollería", "🧁", "ud", None),
    ("Pan integral", "Panadería y Bollería", "🍞", "ud", None),
    ("Bollos de leche", "Panadería y Bollería", "🥐", "ud", None),
    ("Donuts", "Panadería y Bollería", "🍩", "ud", None),
    ("Tortitas", "Panadería y Bollería", "🥞", "pack", None),
    ("Empanadillas", "Panadería y Bollería", "🥟", "pack", None),
    ("Pan de hamburguesa", "Panadería y Bollería", "🍔", "pack", None),
    ("Pan de pita", "Panadería y Bollería", "🫓", "pack", None),
    ("Tortillas de trigo", "Panadería y Bollería", "🫓", "pack", None),
    ("Bizcocho", "Panadería y Bollería", "🍰", "ud", None),
    ("Ensaimada", "Panadería y Bollería", "🥐", "ud", None),
    ("Palmeras de chocolate", "Panadería y Bollería", "🥐", "ud", None),
    ("Colines", "Panadería y Bollería", "🥖", "pack", None),
    # Lácteos y Huevos
    ("Leche entera", "Lácteos y Huevos", "🥛", "l", "Brick 1L"),
    ("Leche desnatada", "Lácteos y Huevos", "🥛", "l", "Brick 1L"),
    ("Huevos", "Lácteos y Huevos", "🥚", "docena", None),
    ("Yogur natural", "Lácteos y Huevos", "🍮", "pack", None),
    ("Queso", "Lácteos y Huevos", "🧀", "ud", None),
    ("Mantequilla", "Lácteos y Huevos", "🧈", "ud", None),
    ("Nata para cocinar", "Lácteos y Huevos", "🥛", "ud", None),
    ("Leche semidesnatada", "Lácteos y Huevos", "🥛", "l", "Brick 1L"),
    ("Yogur de sabores", "Lácteos y Huevos", "🍮", "pack", None),
    ("Queso rallado", "Lácteos y Huevos", "🧀", "ud", None),
    ("Queso fresco", "Lácteos y Huevos", "🧀", "ud", None),
    ("Actimel", "Lácteos y Huevos", "🍮", "pack", None),
    ("Cuajada", "Lácteos y Huevos", "🍮", "ud", None),
    ("Leche sin lactosa", "Lácteos y Huevos", "🥛", "l", "Brick 1L"),
    ("Mozzarella", "Lácteos y Huevos", "🧀", "ud", None),
    ("Queso parmesano", "Lácteos y Huevos", "🧀", "ud", None),
    ("Requesón", "Lácteos y Huevos", "🧀", "ud", None),
    ("Flan", "Lácteos y Huevos", "🍮", "pack", None),
    ("Natillas", "Lácteos y Huevos", "🍮", "pack", None),
    ("Nata montada", "Lácteos y Huevos", "🥛", "ud", None),
    # Carnes y Embutidos
    ("Pechuga de pollo", "Carnes y Embutidos", "🍗", "kg", None),
    ("Carne picada", "Carnes y Embutidos", "🥩", "kg", None),
    ("Filetes de ternera", "Carnes y Embutidos", "🥩", "kg", None),
    ("Jamón cocido", "Carnes y Embutidos", "🥓", "ud", None),
    ("Jamón serrano", "Carnes y Embutidos", "🍖", "ud", None),
    ("Chorizo", "Carnes y Embutidos", "🌭", "ud", None),
    ("Salchichas", "Carnes y Embutidos", "🌭", "ud", None),
    ("Bacon", "Carnes y Embutidos", "🥓", "ud", None),
    ("Muslos de pollo", "Carnes y Embutidos", "🍗", "kg", None),
    ("Alitas de pollo", "Carnes y Embutidos", "🍗", "kg", None),
    ("Lomo de cerdo", "Carnes y Embutidos", "🥩", "kg", None),
    ("Costillas", "Carnes y Embutidos", "🍖", "kg", None),
    ("Salchichón", "Carnes y Embutidos", "🍖", "ud", None),
    ("Mortadela", "Carnes y Embutidos", "🍖", "ud", None),
    ("Pavo en lonchas", "Carnes y Embutidos", "🦃", "ud", None),
    ("Pollo entero", "Carnes y Embutidos", "🍗", "kg", None),
    ("Solomillo de cerdo", "Carnes y Embutidos", "🥩", "kg", None),
    ("Morcilla", "Carnes y Embutidos", "🍖", "ud", None),
    ("Sobrasada", "Carnes y Embutidos", "🍖", "ud", None),
    ("Panceta", "Carnes y Embutidos", "🥓", "kg", None),
    ("Salami", "Carnes y Embutidos", "🍖", "ud", None),
    # Pescados y Mariscos
    ("Salmón", "Pescados y Mariscos", "🐟", "kg", None),
    ("Merluza", "Pescados y Mariscos", "🐟", "kg", None),
    ("Atún en lata", "Pescados y Mariscos", "🥫", "pack", None),
    ("Gambas", "Pescados y Mariscos", "🦐", "kg", None),
    ("Bacalao", "Pescados y Mariscos", "🐟", "kg", None),
    ("Sardinas", "Pescados y Mariscos", "🐟", "kg", None),
    ("Boquerones", "Pescados y Mariscos", "🐟", "kg", None),
    ("Calamares", "Pescados y Mariscos", "🦑", "kg", None),
    ("Mejillones", "Pescados y Mariscos", "🦪", "kg", None),
    ("Pulpo", "Pescados y Mariscos", "🐙", "kg", None),
    ("Lenguado", "Pescados y Mariscos", "🐟", "kg", None),
    ("Dorada", "Pescados y Mariscos", "🐟", "kg", None),
    ("Sepia", "Pescados y Mariscos", "🦑", "kg", None),
    ("Almejas", "Pescados y Mariscos", "🦪", "kg", None),
    ("Berberechos en lata", "Pescados y Mariscos", "🥫", "ud", None),
    ("Mejillones en lata", "Pescados y Mariscos", "🥫", "ud", None),
    # Congelados
    ("Guisantes congelados", "Congelados", "🧊", "ud", None),
    ("Verdura congelada", "Congelados", "🧊", "ud", None),
    ("Pizza congelada", "Congelados", "🍕", "ud", None),
    ("Helado", "Congelados", "🍦", "ud", None),
    ("Croquetas congeladas", "Congelados", "🧊", "ud", None),
    ("Patatas fritas congeladas", "Congelados", "🍟", "ud", None),
    ("Palitos de pescado", "Congelados", "🐟", "ud", None),
    ("Rebozados congelados", "Congelados", "🧊", "ud", None),
    ("Empanadillas congeladas", "Congelados", "🥟", "ud", None),
    ("Gambas congeladas", "Congelados", "🦐", "kg", None),
    ("Masa de hojaldre", "Congelados", "🧊", "ud", None),
    ("Langostinos congelados", "Congelados", "🦐", "kg", None),
    ("Tarta helada", "Congelados", "🍰", "ud", None),
    ("Salteado de verduras congelado", "Congelados", "🧊", "ud", None),
    # Despensa
    ("Aceite de oliva", "Despensa", "🫒", "ud", None),
    ("Arroz", "Despensa", "🍚", "kg", None),
    ("Lentejas", "Despensa", "🥫", "ud", None),
    ("Garbanzos", "Despensa", "🥫", "ud", None),
    ("Tomate frito", "Despensa", "🥫", "ud", None),
    ("Sal", "Despensa", "🧂", "ud", None),
    ("Azúcar", "Despensa", "🧂", "kg", None),
    ("Harina", "Despensa", "🌾", "kg", None),
    ("Miel", "Despensa", "🍯", "ud", None),
    ("Vinagre", "Despensa", "🍶", "ud", None),
    ("Aceite de girasol", "Despensa", "🫙", "ud", None),
    ("Alubias", "Despensa", "🥫", "ud", None),
    ("Caldo en pastillas", "Despensa", "🧂", "ud", None),
    ("Especias variadas", "Despensa", "🌿", "ud", None),
    ("Pimentón", "Despensa", "🌶️", "ud", None),
    ("Mayonesa", "Despensa", "🥫", "ud", None),
    ("Ketchup", "Despensa", "🥫", "ud", None),
    ("Mostaza", "Despensa", "🥫", "ud", None),
    ("Levadura", "Despensa", "🌾", "ud", None),
    ("Maíz en lata", "Despensa", "🌽", "ud", None),
    ("Aceitunas", "Despensa", "🫒", "ud", None),
    ("Pepinillos", "Despensa", "🥒", "ud", None),
    ("Salsa barbacoa", "Despensa", "🥫", "ud", None),
    ("Alioli", "Despensa", "🥫", "ud", None),
    ("Salsa de soja", "Despensa", "🥫", "ud", None),
    ("Cacao en polvo", "Despensa", "🍫", "ud", None),
    ("Gelatina", "Despensa", "🍮", "ud", None),
    ("Pasta de tomate", "Despensa", "🥫", "ud", None),
    # Cereales y Pasta
    ("Espaguetis", "Cereales y Pasta", "🍜", "ud", None),
    ("Macarrones", "Cereales y Pasta", "🍜", "ud", None),
    ("Cereales de desayuno", "Cereales y Pasta", "🥣", "ud", None),
    ("Copos de avena", "Cereales y Pasta", "🥣", "ud", None),
    ("Galletas", "Cereales y Pasta", "🍪", "ud", None),
    ("Fideos", "Cereales y Pasta", "🍜", "ud", None),
    ("Arroz integral", "Cereales y Pasta", "🍚", "kg", None),
    ("Quinoa", "Cereales y Pasta", "🍚", "ud", None),
    ("Muesli", "Cereales y Pasta", "🥣", "ud", None),
    ("Tostadas", "Cereales y Pasta", "🍞", "ud", None),
    ("Arroz bomba", "Cereales y Pasta", "🍚", "kg", None),
    ("Cuscús", "Cereales y Pasta", "🍚", "ud", None),
    ("Pasta integral", "Cereales y Pasta", "🍜", "ud", None),
    ("Lasaña (placas)", "Cereales y Pasta", "🍝", "ud", None),
    ("Canelones (placas)", "Cereales y Pasta", "🍝", "ud", None),
    # Snacks y Dulces
    ("Patatas fritas", "Snacks y Dulces", "🍟", "ud", None),
    ("Palomitas", "Snacks y Dulces", "🍿", "ud", None),
    ("Chocolate", "Snacks y Dulces", "🍫", "ud", None),
    ("Frutos secos", "Snacks y Dulces", "🥜", "ud", None),
    ("Caramelos", "Snacks y Dulces", "🍬", "ud", None),
    ("Gominolas", "Snacks y Dulces", "🍬", "ud", None),
    ("Barritas de cereales", "Snacks y Dulces", "🍫", "ud", None),
    ("Turrón", "Snacks y Dulces", "🍫", "ud", None),
    ("Nachos", "Snacks y Dulces", "🌽", "ud", None),
    ("Gusanitos", "Snacks y Dulces", "🍟", "ud", None),
    ("Aceitunas rellenas", "Snacks y Dulces", "🫒", "ud", None),
    ("Regaliz", "Snacks y Dulces", "🍬", "ud", None),
    ("Tortitas de arroz", "Snacks y Dulces", "🍘", "ud", None),
    ("Almendras", "Snacks y Dulces", "🥜", "ud", None),
    ("Pistachos", "Snacks y Dulces", "🥜", "ud", None),
    # Bebidas
    ("Agua mineral", "Bebidas", "💧", "pack", None),
    ("Refrescos de cola", "Bebidas", "🥤", "ud", None),
    ("Zumo de naranja", "Bebidas", "🧃", "ud", None),
    ("Cerveza", "Bebidas", "🍺", "pack", None),
    ("Vino", "Bebidas", "🍷", "ud", None),
    ("Café", "Bebidas", "☕", "ud", None),
    ("Té", "Bebidas", "🍵", "ud", None),
    ("Refresco de limón", "Bebidas", "🥤", "ud", None),
    ("Bebida isotónica", "Bebidas", "🥤", "ud", None),
    ("Cava", "Bebidas", "🍾", "ud", None),
    ("Zumo de piña", "Bebidas", "🧃", "ud", None),
    ("Batido de chocolate", "Bebidas", "🥤", "ud", None),
    ("Cola cao", "Bebidas", "🍫", "ud", None),
    ("Agua con gas", "Bebidas", "💧", "pack", None),
    ("Cápsulas de café", "Bebidas", "☕", "pack", None),
    ("Leche de avena", "Bebidas", "🥛", "l", None),
    ("Leche de almendra", "Bebidas", "🥛", "l", None),
    ("Horchata", "Bebidas", "🥤", "ud", None),
    ("Vermut", "Bebidas", "🍷", "ud", None),
    ("Sidra", "Bebidas", "🍾", "ud", None),
    ("Whisky", "Bebidas", "🥃", "ud", None),
    ("Ron", "Bebidas", "🥃", "ud", None),
    ("Ginebra", "Bebidas", "🥃", "ud", None),
    ("Infusiones", "Bebidas", "🍵", "pack", None),
    # Limpieza
    ("Detergente lavadora", "Limpieza", "🧴", "ud", None),
    ("Suavizante", "Limpieza", "🧴", "ud", None),
    ("Lejía", "Limpieza", "🧴", "ud", None),
    ("Limpiacristales", "Limpieza", "🧴", "ud", None),
    ("Papel de cocina", "Limpieza", "🧻", "ud", None),
    ("Bolsas de basura", "Limpieza", "🗑️", "pack", None),
    ("Estropajo", "Limpieza", "🧽", "ud", None),
    ("Friegasuelos", "Limpieza", "🪣", "ud", None),
    ("Lavavajillas", "Limpieza", "🧴", "ud", None),
    ("Guantes de goma", "Limpieza", "🧤", "ud", None),
    ("Ambientador", "Limpieza", "🧴", "ud", None),
    ("Quitagrasas", "Limpieza", "🧴", "ud", None),
    ("Papel film", "Limpieza", "🧻", "ud", None),
    ("Papel de aluminio", "Limpieza", "🧻", "ud", None),
    ("Bayetas", "Limpieza", "🧽", "pack", None),
    ("Insecticida", "Limpieza", "🧴", "ud", None),
    ("Desatascador líquido", "Limpieza", "🧴", "ud", None),
    ("Bolsas de congelación", "Limpieza", "🧊", "pack", None),
    ("Vinagre de limpieza", "Limpieza", "🧴", "ud", None),
    ("Pastillas lavavajillas", "Limpieza", "🧴", "pack", None),
    # Higiene
    ("Papel higiénico", "Higiene", "🧻", "pack", None),
    ("Gel de ducha", "Higiene", "🧴", "ud", None),
    ("Champú", "Higiene", "🧴", "ud", None),
    ("Pasta de dientes", "Higiene", "🪥", "ud", None),
    ("Desodorante", "Higiene", "🧴", "ud", None),
    ("Cepillo de dientes", "Higiene", "🪥", "ud", None),
    ("Enjuague bucal", "Higiene", "🧴", "ud", None),
    ("Crema hidratante", "Higiene", "🧴", "ud", None),
    ("Cuchillas de afeitar", "Higiene", "🪒", "ud", None),
    ("Compresas", "Higiene", "🧴", "pack", None),
    ("Tampones", "Higiene", "🧴", "pack", None),
    ("Toallitas desmaquillantes", "Higiene", "🧴", "pack", None),
    ("Colonia", "Higiene", "🧴", "ud", None),
    ("Protector solar", "Higiene", "🧴", "ud", None),
    ("Crema de manos", "Higiene", "🧴", "ud", None),
    ("Hilo dental", "Higiene", "🪥", "ud", None),
    ("Algodón", "Higiene", "🧴", "ud", None),
    ("Bastoncillos", "Higiene", "🧴", "pack", None),
    ("Gel antibacterial", "Higiene", "🧴", "ud", None),
    ("Maquinillas desechables", "Higiene", "🪒", "pack", None),
    # Bebé
    ("Pañales", "Bebé", "🍼", "pack", None),
    ("Toallitas húmedas", "Bebé", "🍼", "pack", None),
    ("Leche de fórmula", "Bebé", "🍼", "ud", None),
    ("Potitos", "Bebé", "🍼", "ud", None),
    ("Papilla de cereales", "Bebé", "🍼", "ud", None),
    ("Crema para el culito", "Bebé", "🍼", "ud", None),
    ("Toallitas de baño", "Bebé", "🍼", "pack", None),
    ("Biberones", "Bebé", "🍼", "ud", None),
    ("Chupetes", "Bebé", "🍼", "ud", None),
    ("Potitos de fruta", "Bebé", "🍼", "ud", None),
    ("Colonia para bebé", "Bebé", "🍼", "ud", None),
    # Mascotas
    ("Pienso para perro", "Mascotas", "🐶", "kg", None),
    ("Pienso para gato", "Mascotas", "🐱", "kg", None),
    ("Arena para gatos", "Mascotas", "🐱", "ud", None),
    ("Snacks para mascotas", "Mascotas", "🦴", "ud", None),
    ("Comida húmeda para gato", "Mascotas", "🐱", "ud", None),
    ("Comida húmeda para perro", "Mascotas", "🐶", "ud", None),
    ("Bolsas para excrementos", "Mascotas", "🐶", "pack", None),
    ("Snacks dentales para perro", "Mascotas", "🦴", "ud", None),
    ("Champú para mascotas", "Mascotas", "🐶", "ud", None),
    ("Arena aglomerante", "Mascotas", "🐱", "ud", None),
    # Hogar
    ("Bombillas", "Hogar", "💡", "ud", None),
    ("Pilas AA", "Hogar", "🔋", "pack", None),
    ("Pilas AAA", "Hogar", "🔋", "pack", None),
    ("Velas", "Hogar", "🕯️", "ud", None),
    ("Cerillas", "Hogar", "🔥", "ud", None),
    ("Mechero", "Hogar", "🔥", "ud", None),
    ("Pinzas de tender", "Hogar", "🧺", "pack", None),
    ("Bolsas de vacío", "Hogar", "🧺", "pack", None),
    ("Ambientador eléctrico (recambio)", "Hogar", "🏠", "ud", None),
    ("Cinta adhesiva", "Hogar", "🏠", "ud", None),
    # Farmacia y Botiquín
    ("Paracetamol", "Farmacia y Botiquín", "💊", "ud", None),
    ("Ibuprofeno", "Farmacia y Botiquín", "💊", "ud", None),
    ("Tiritas", "Farmacia y Botiquín", "🩹", "pack", None),
    ("Gasas estériles", "Farmacia y Botiquín", "🩹", "pack", None),
    ("Alcohol antiséptico", "Farmacia y Botiquín", "💊", "ud", None),
    ("Agua oxigenada", "Farmacia y Botiquín", "💊", "ud", None),
    ("Termómetro", "Farmacia y Botiquín", "🌡️", "ud", None),
    ("Suero fisiológico", "Farmacia y Botiquín", "💊", "ud", None),
    ("Mascarillas", "Farmacia y Botiquín", "😷", "pack", None),
    # Bazar (bazar/tienda de todo a cien)
    ("Vasos de plástico", "Bazar", "🥤", "pack", None),
    ("Platos de plástico", "Bazar", "🍽️", "pack", None),
    ("Cubiertos de plástico", "Bazar", "🍽️", "pack", None),
    ("Manteles desechables", "Bazar", "🧻", "ud", None),
    ("Servilletas de papel", "Bazar", "🧻", "pack", None),
    ("Velas decorativas", "Bazar", "🕯️", "ud", None),
    ("Globos", "Bazar", "🎈", "pack", None),
    ("Papel de regalo", "Bazar", "🎁", "ud", None),
    ("Cinta adhesiva decorativa", "Bazar", "🎀", "ud", None),
    ("Pinceles", "Bazar", "🖌️", "ud", None),
    ("Pinturas acrílicas", "Bazar", "🎨", "ud", None),
    ("Hilo y aguja (costurero)", "Bazar", "🧵", "ud", None),
    ("Imperdibles", "Bazar", "🧷", "pack", None),
    ("Perchas", "Bazar", "👕", "pack", None),
    ("Marcos de fotos", "Bazar", "🖼️", "ud", None),
    ("Paraguas", "Bazar", "☂️", "ud", None),
    ("Pilas de botón", "Bazar", "🔋", "pack", None),
    ("Cargador de móvil", "Bazar", "🔌", "ud", None),
    ("Bolsas reutilizables", "Bazar", "🧺", "ud", None),
    ("Organizadores de plástico", "Bazar", "📦", "ud", None),
    # Ferretería
    ("Bombillas LED", "Ferretería", "💡", "ud", None),
    ("Pilas AA", "Ferretería", "🔋", "pack", None),
    ("Pilas AAA", "Ferretería", "🔋", "pack", None),
    ("Destornillador", "Ferretería", "🪛", "ud", None),
    ("Martillo", "Ferretería", "🔨", "ud", None),
    ("Alicates", "Ferretería", "🔧", "ud", None),
    ("Llave inglesa", "Ferretería", "🔧", "ud", None),
    ("Tornillos", "Ferretería", "🔩", "pack", None),
    ("Tacos de plástico", "Ferretería", "🔩", "pack", None),
    ("Clavos", "Ferretería", "🔩", "pack", None),
    ("Cinta métrica", "Ferretería", "📏", "ud", None),
    ("Cúter", "Ferretería", "🔪", "ud", None),
    ("Cinta aislante", "Ferretería", "🧰", "ud", None),
    ("Cinta americana", "Ferretería", "🧰", "ud", None),
    ("Silicona/sellador", "Ferretería", "🧴", "ud", None),
    ("Pegamento universal", "Ferretería", "🧴", "ud", None),
    ("Bridas de plástico", "Ferretería", "🔗", "pack", None),
    ("Cuerda/cordel", "Ferretería", "🔗", "ud", None),
    ("Candado", "Ferretería", "🔑", "ud", None),
    ("Alargador eléctrico", "Ferretería", "🔌", "ud", None),
    ("Regleta enchufes", "Ferretería", "🔌", "ud", None),
    ("Linterna", "Ferretería", "🔦", "ud", None),
    ("Guantes de trabajo", "Ferretería", "🧤", "pack", None),
    ("Mascarilla de protección", "Ferretería", "😷", "pack", None),
    ("Gafas de protección", "Ferretería", "🥽", "ud", None),
    ("Fusibles", "Ferretería", "🔌", "pack", None),
    ("Bisagras", "Ferretería", "🔧", "ud", None),
    ("Trampa para ratones", "Ferretería", "🪤", "ud", None),
    ("Imanes", "Ferretería", "🧲", "pack", None),
    ("Aceite lubricante (WD-40)", "Ferretería", "🧴", "ud", None),
    ("Sierra manual", "Ferretería", "🪚", "ud", None),
    # Despensa (ampliación)
    ("Pimienta negra", "Despensa", "🧂", "ud", None),
    ("Orégano", "Despensa", "🌿", "ud", None),
    ("Comino", "Despensa", "🌿", "ud", None),
    ("Cúrcuma", "Despensa", "🌿", "ud", None),
    ("Tomillo", "Despensa", "🌿", "ud", None),
    ("Romero", "Despensa", "🌿", "ud", None),
    ("Laurel", "Despensa", "🌿", "ud", None),
    ("Canela en polvo", "Despensa", "🌿", "ud", None),
    ("Nuez moscada", "Despensa", "🌿", "ud", None),
    ("Ajo en polvo", "Despensa", "🧂", "ud", None),
    ("Perejil seco", "Despensa", "🌿", "ud", None),
    ("Curry en polvo", "Despensa", "🌿", "ud", None),
    ("Pipas de girasol", "Despensa", "🌻", "ud", None),
    ("Nueces", "Despensa", "🥜", "ud", None),
    ("Anacardos", "Despensa", "🥜", "ud", None),
    ("Semillas de chía", "Despensa", "🌱", "ud", None),
    ("Semillas de lino", "Despensa", "🌱", "ud", None),
    ("Pimientos asados en conserva", "Despensa", "🥫", "ud", None),
    ("Espárragos en conserva", "Despensa", "🥫", "ud", None),
    ("Judías blancas cocidas", "Despensa", "🥫", "ud", None),
    ("Piña en almíbar", "Despensa", "🥫", "ud", None),
    ("Melocotón en almíbar", "Despensa", "🥫", "ud", None),
    ("Salsa brava", "Despensa", "🥫", "ud", None),
    ("Salsa romesco", "Despensa", "🥫", "ud", None),
    ("Salsa pesto", "Despensa", "🥫", "ud", None),
    ("Salsa picante", "Despensa", "🥫", "ud", None),
    ("Salsa César", "Despensa", "🥫", "ud", None),
    ("Sopa de sobre", "Despensa", "🥣", "ud", None),
    ("Crema de verduras", "Despensa", "🥣", "ud", None),
    ("Gazpacho", "Despensa", "🥣", "l", None),
    ("Caldo de pollo (brick)", "Despensa", "🥫", "l", None),
    ("Caldo de verduras (brick)", "Despensa", "🥫", "l", None),
    ("Edulcorante", "Despensa", "🧂", "ud", None),
    ("Aceite de coco", "Despensa", "🥥", "ud", None),
    # Alternativas Vegetales
    ("Tofu", "Alternativas Vegetales", "🧊", "ud", None),
    ("Seitán", "Alternativas Vegetales", "🌱", "ud", None),
    ("Hamburguesas vegetales", "Alternativas Vegetales", "🍔", "pack", None),
    ("Leche de soja", "Alternativas Vegetales", "🥛", "l", None),
    ("Leche de coco", "Alternativas Vegetales", "🥛", "l", None),
    ("Yogur de soja", "Alternativas Vegetales", "🍮", "pack", None),
    ("Queso vegano", "Alternativas Vegetales", "🧀", "ud", None),
    ("Salchichas vegetales", "Alternativas Vegetales", "🌭", "pack", None),
    ("Bebida de avena", "Alternativas Vegetales", "🥛", "l", None),
    ("Nata vegetal para cocinar", "Alternativas Vegetales", "🥛", "ud", None),
    # Bebidas (ampliación)
    ("Zumo de manzana", "Bebidas", "🧃", "ud", None),
    ("Zumo de tomate", "Bebidas", "🧃", "ud", None),
    ("Bebida energética", "Bebidas", "🥤", "ud", None),
    ("Refresco de naranja", "Bebidas", "🥤", "ud", None),
    ("Tónica", "Bebidas", "🥤", "ud", None),
    # Limpieza (ampliación)
    ("Jabón de manos", "Limpieza", "🧴", "ud", None),
    ("Quitamanchas", "Limpieza", "🧴", "ud", None),
    ("Toallitas de limpieza multiusos", "Limpieza", "🧻", "pack", None),
    ("Ambientador para coche", "Limpieza", "🧴", "ud", None),
    # Higiene (ampliación)
    ("Mascarilla facial de belleza", "Higiene", "🧴", "ud", None),
    ("Espuma de afeitar", "Higiene", "🧴", "ud", None),
    ("Toallitas húmedas de higiene íntima", "Higiene", "🧴", "pack", None),
    # Frutas y Verduras (ampliación: variedades de hoja verde y frutas que
    # faltaban, revisado contra el surtido real de supermercados españoles)
    ("Pomelo", "Frutas y Verduras", "citrus", "kg", None),
    ("Lima", "Frutas y Verduras", "citrus", "ud", None),
    ("Nectarinas", "Frutas y Verduras", "cherry", "kg", None),
    ("Frambuesas", "Frutas y Verduras", "cherry", "ud", None),
    ("Moras", "Frutas y Verduras", "cherry", "ud", None),
    ("Arándanos", "Frutas y Verduras", "cherry", "ud", None),
    ("Paraguayos", "Frutas y Verduras", "cherry", "kg", None),
    ("Albaricoques", "Frutas y Verduras", "cherry", "kg", None),
    ("Cogollos de lechuga", "Frutas y Verduras", "salad", "ud", None),
    ("Lechuga hoja de roble", "Frutas y Verduras", "salad", "ud", None),
    ("Canónigos", "Frutas y Verduras", "salad", "ud", "Bolsa"),
    ("Endibias", "Frutas y Verduras", "salad", "ud", None),
    ("Brotes verdes (mezcla de ensalada)", "Frutas y Verduras", "salad", "ud", "Bolsa"),
    ("Espinacas baby", "Frutas y Verduras", "salad", "ud", "Bolsa"),
    ("Acelgas", "Frutas y Verduras", "salad", "ud", None),
    ("Repollo", "Frutas y Verduras", "salad", "ud", None),
    ("Col kale", "Frutas y Verduras", "salad", "ud", None),
    ("Cebolleta", "Frutas y Verduras", "sprout", "ud", None),
    ("Cebollino", "Frutas y Verduras", "leaf", "ud", None),
    ("Maíz dulce en mazorca", "Frutas y Verduras", "carrot", "ud", None),
    ("Verduras troceadas para cocinar", "Frutas y Verduras", "salad", "ud", "Bolsa lista para cocinar"),
    ("Albahaca fresca", "Frutas y Verduras", "leaf", "ud", None),
    ("Cilantro fresco", "Frutas y Verduras", "leaf", "ud", None),
    ("Perejil fresco", "Frutas y Verduras", "leaf", "ud", None),
    ("Menta fresca", "Frutas y Verduras", "leaf", "ud", None),
    ("Jengibre", "Frutas y Verduras", "sprout", "ud", None),
    ("Boniato", "Frutas y Verduras", "carrot", "kg", None),
    ("Yuca", "Frutas y Verduras", "carrot", "kg", None),
    ("Nabo", "Frutas y Verduras", "carrot", "kg", None),
    ("Chalotas", "Frutas y Verduras", "sprout", "kg", None),
    ("Chirimoya", "Frutas y Verduras", "cherry", "ud", None),
    ("Papaya", "Frutas y Verduras", "cherry", "ud", None),
    ("Mango", "Frutas y Verduras", "cherry", "ud", None),
    ("Coco", "Frutas y Verduras", "nut", "ud", None),
    ("Dátiles", "Frutas y Verduras", "nut", "ud", None),
    ("Higos secos", "Frutas y Verduras", "nut", "ud", None),
    ("Setas variadas", "Frutas y Verduras", "salad", "kg", None),
    ("Rúcula", "Frutas y Verduras", "salad", "ud", None),
    ("Escarola", "Frutas y Verduras", "salad", "ud", None),
    # Panadería y Bollería (ampliación)
    ("Pan rallado", "Panadería y Bollería", "wheat", "ud", None),
    ("Picos / regañás", "Panadería y Bollería", "wheat", "pack", None),
    ("Grissini", "Panadería y Bollería", "wheat", "pack", None),
    ("Bollos suizos", "Panadería y Bollería", "croissant", "pack", None),
    ("Napolitanas de chocolate", "Panadería y Bollería", "croissant", "ud", None),
    ("Roscón", "Panadería y Bollería", "cake", "ud", None),
    ("Pan de centeno", "Panadería y Bollería", "wheat", "ud", None),
    ("Pan sin gluten", "Panadería y Bollería", "wheat-off", "ud", None),
    # Lácteos, Huevos y Quesos (ampliación)
    ("Queso curado", "Lácteos y Huevos", "wheat", "ud", None),
    ("Queso semicurado", "Lácteos y Huevos", "wheat", "ud", None),
    ("Queso azul", "Lácteos y Huevos", "wheat", "ud", None),
    ("Queso de cabra", "Lácteos y Huevos", "wheat", "ud", None),
    ("Queso en lonchas", "Lácteos y Huevos", "wheat", "pack", None),
    ("Queso para untar", "Lácteos y Huevos", "wheat", "ud", None),
    ("Leche condensada", "Lácteos y Huevos", "milk", "ud", None),
    ("Leche evaporada", "Lácteos y Huevos", "milk", "ud", None),
    ("Claras de huevo", "Lácteos y Huevos", "egg", "ud", "Brick"),
    ("Huevos camperos", "Lácteos y Huevos", "egg", "docena", None),
    # Carnes, Embutidos y Charcutería (ampliación)
    ("Paté", "Carnes y Embutidos", "drumstick", "ud", None),
    ("Foie", "Carnes y Embutidos", "drumstick", "ud", None),
    ("Jamón ibérico", "Carnes y Embutidos", "drumstick", "ud", None),
    ("Butifarra", "Carnes y Embutidos", "sandwich", "ud", None),
    ("Longaniza", "Carnes y Embutidos", "sandwich", "ud", None),
    ("Fuet", "Carnes y Embutidos", "sandwich", "ud", None),
    ("Cecina", "Carnes y Embutidos", "beef", "ud", None),
    ("Fiambre de pavo", "Carnes y Embutidos", "drumstick", "ud", None),
    ("Salchichas Frankfurt", "Carnes y Embutidos", "sandwich", "pack", None),
    ("Carne de cerdo troceada", "Carnes y Embutidos", "beef", "kg", None),
    ("Costillas adobadas", "Carnes y Embutidos", "beef", "kg", None),
    ("Pincho moruno", "Carnes y Embutidos", "drumstick", "kg", None),
    # Pescados y Mariscos (ampliación)
    ("Rape", "Pescados y Mariscos", "fish", "kg", None),
    ("Rodaballo", "Pescados y Mariscos", "fish", "kg", None),
    ("Caballa", "Pescados y Mariscos", "fish", "kg", None),
    ("Langostinos frescos", "Pescados y Mariscos", "fish-symbol", "kg", None),
    ("Percebes", "Pescados y Mariscos", "fish-symbol", "kg", None),
    ("Angulas / gulas", "Pescados y Mariscos", "fish-symbol", "ud", None),
    # Congelados (ampliación)
    ("Filetes de pescado congelado", "Congelados", "fish", "kg", None),
    ("Marisco congelado variado", "Congelados", "fish-symbol", "kg", None),
    ("Alitas de pollo congeladas", "Congelados", "drumstick", "kg", None),
    ("Nuggets de pollo", "Congelados", "drumstick", "ud", None),
    ("Hamburguesas congeladas", "Congelados", "sandwich", "ud", None),
    ("Polos de hielo", "Congelados", "ice-cream-cone", "pack", None),
    ("Tarta de queso congelada", "Congelados", "cake", "ud", None),
    ("Base de pizza congelada", "Congelados", "pizza", "ud", None),
    ("Frutos rojos congelados", "Congelados", "cherry", "pack", None),
    ("Sepia congelada", "Congelados", "fish-symbol", "kg", None),
    # Despensa y Conservas (ampliación)
    ("Mermelada", "Despensa", "cake-slice", "ud", None),
    ("Crema de cacao para untar", "Despensa", "cake-slice", "ud", None),
    ("Mantequilla de cacahuete", "Despensa", "nut", "ud", None),
    ("Anchoas en lata", "Despensa", "fish", "ud", None),
    ("Sardinillas en lata", "Despensa", "fish", "ud", None),
    ("Caballa en lata", "Despensa", "fish", "ud", None),
    ("Arroz preparado", "Despensa", "soup", "ud", "Sobre"),
    ("Falafel (mezcla)", "Despensa", "salad", "ud", None),
    ("Hummus", "Despensa", "salad", "ud", None),
    ("Guacamole envasado", "Despensa", "salad", "ud", None),
    ("Vinagre balsámico", "Despensa", "wine", "ud", None),
    ("Aceite de sésamo", "Despensa", "droplet", "ud", None),
    ("Leche de arroz", "Despensa", "milk", "ud", None),
    ("Azafrán", "Despensa", "sprout", "ud", None),
    ("Guindilla", "Despensa", "sprout", "ud", None),
    # Snacks y Dulces (ampliación)
    ("Chocolatinas variadas", "Snacks y Dulces", "candy-cane", "ud", None),
    ("Chicles", "Snacks y Dulces", "candy", "pack", None),
    ("Piruletas", "Snacks y Dulces", "candy", "pack", None),
    ("Bombones", "Snacks y Dulces", "candy-cane", "ud", None),
    ("Barquillos", "Snacks y Dulces", "cookie", "pack", None),
    ("Palmeritas de hojaldre", "Snacks y Dulces", "croissant", "pack", None),
    ("Kikos (maíz frito)", "Snacks y Dulces", "popcorn", "ud", None),
    ("Snacks de queso", "Snacks y Dulces", "popcorn", "ud", None),
    # Bebidas (ampliación)
    ("Licor 43", "Bebidas", "martini", "ud", None),
    ("Sangría", "Bebidas", "wine", "ud", None),
    ("Gaseosa", "Bebidas", "cup-soda", "ud", None),
    ("Mosto", "Bebidas", "wine", "ud", None),
    ("Batido de fresa", "Bebidas", "cup-soda", "ud", None),
    ("Batido de vainilla", "Bebidas", "cup-soda", "ud", None),
    ("Café soluble", "Bebidas", "coffee", "ud", None),
    ("Café en grano", "Bebidas", "coffee", "ud", None),
    ("Bebida de arroz", "Bebidas", "milk", "l", None),
    ("Vino dulce / Moscatel", "Bebidas", "wine", "ud", None),
    # Limpieza (ampliación)
    ("Desinfectante multiusos", "Limpieza", "spray-can", "ud", None),
    ("Limpiador de baño", "Limpieza", "spray-can", "ud", None),
    ("Limpiador de horno", "Limpieza", "spray-can", "ud", None),
    ("Pastillas WC", "Limpieza", "toilet", "ud", None),
    ("Desatascador (ventosa)", "Limpieza", "toilet", "ud", None),
    ("Bolsas para aspiradora", "Limpieza", "container", "pack", None),
    ("Filtro de aspiradora", "Limpieza", "container", "ud", None),
    ("Limpiador multisuperficies", "Limpieza", "spray-can", "ud", None),
    ("Estropajo de acero", "Limpieza", "waves-ladder", "pack", None),
    ("Quitaóxido", "Limpieza", "spray-can", "ud", None),
    ("Bayetas de microfibra", "Limpieza", "container", "pack", None),
    ("Recambio de fregona", "Limpieza", "container", "ud", None),
    ("Cubo de fregona", "Limpieza", "container", "ud", None),
    # Higiene (ampliación)
    ("After sun", "Higiene", "spray-can", "ud", None),
    ("Repelente de mosquitos", "Higiene", "spray-can", "ud", None),
    ("Crema antiarrugas", "Higiene", "spray-can", "ud", None),
    ("Esponja de baño", "Higiene", "container", "ud", None),
    ("Cera depilatoria", "Higiene", "spray-can", "ud", None),
    ("Cortaúñas", "Higiene", "scissors", "ud", None),
    ("Lima de uñas", "Higiene", "scissors", "ud", None),
    ("Peine / cepillo de pelo", "Higiene", "sparkles", "ud", None),
    ("Gomas de pelo", "Higiene", "sparkles", "pack", None),
    ("Gel íntimo", "Higiene", "spray-can", "ud", None),
    # Farmacia y Botiquín (ampliación)
    ("Vendas elásticas", "Farmacia y Botiquín", "bandage", "ud", None),
    ("Esparadrapo", "Farmacia y Botiquín", "bandage", "ud", None),
    ("Jarabe para la tos", "Farmacia y Botiquín", "pill-bottle", "ud", None),
    ("Antihistamínico", "Farmacia y Botiquín", "pill", "ud", None),
    ("Antiácido", "Farmacia y Botiquín", "pill", "ud", None),
    ("Sales de rehidratación", "Farmacia y Botiquín", "pill", "ud", None),
    ("Crema antiinflamatoria", "Farmacia y Botiquín", "pill-bottle", "ud", None),
    ("Colirio", "Farmacia y Botiquín", "eye", "ud", None),
    ("Gotas para los oídos", "Farmacia y Botiquín", "ear", "ud", None),
    ("Laxante", "Farmacia y Botiquín", "pill", "ud", None),
    ("Probióticos", "Farmacia y Botiquín", "pill", "ud", None),
    ("Multivitamínico", "Farmacia y Botiquín", "pill", "ud", None),
    ("Magnesio", "Farmacia y Botiquín", "pill", "ud", None),
    ("Melatonina", "Farmacia y Botiquín", "pill", "ud", None),
    ("Test de embarazo", "Farmacia y Botiquín", "test-tube", "ud", None),
    ("Test de antígenos", "Farmacia y Botiquín", "test-tube", "ud", None),
    ("Guantes de látex", "Farmacia y Botiquín", "shield-check", "pack", None),
    ("Venda de gasa", "Farmacia y Botiquín", "bandage", "ud", None),
    ("Suero para lentillas", "Farmacia y Botiquín", "droplet", "ud", None),
    # Bebé (ampliación)
    ("Leche de continuación", "Bebé", "milk", "ud", None),
    ("Cereales infantiles", "Bebé", "wheat", "ud", None),
    ("Tazas antigoteo", "Bebé", "baby", "ud", None),
    ("Protector solar infantil", "Bebé", "spray-can", "ud", None),
    ("Champú infantil", "Bebé", "spray-can", "ud", None),
    ("Aceite de bebé", "Bebé", "droplet", "ud", None),
    ("Bolsas para pañales", "Bebé", "baby", "pack", None),
    # Mascotas (ampliación)
    ("Pipetas antiparasitarias", "Mascotas", "dog", "ud", None),
    ("Collar antiparasitario", "Mascotas", "dog", "ud", None),
    ("Correa", "Mascotas", "dog", "ud", None),
    ("Collar", "Mascotas", "dog", "ud", None),
    ("Comedero", "Mascotas", "bone", "ud", None),
    ("Bebedero", "Mascotas", "droplet", "ud", None),
    ("Juguetes para mascotas", "Mascotas", "bone", "ud", None),
    ("Champú antipulgas", "Mascotas", "dog", "ud", None),
    ("Snacks para gato", "Mascotas", "cat", "ud", None),
    ("Alpiste / comida para pájaros", "Mascotas", "bird", "kg", None),
    ("Comida para conejos/roedores", "Mascotas", "rabbit", "kg", None),
    # Bazar (ampliación)
    ("Adaptador de viaje", "Bazar", "plug", "ud", None),
    ("Batería externa (power bank)", "Bazar", "battery-charging", "ud", None),
    ("Auriculares", "Bazar", "headphones", "ud", None),
    ("Funda para móvil", "Bazar", "smartphone", "ud", None),
    ("Espejo de mano", "Bazar", "image", "ud", None),
    ("Reloj de pared", "Bazar", "watch", "ud", None),
    ("Bolsa de viaje", "Bazar", "luggage", "ud", None),
    ("Candado de maleta", "Bazar", "key", "ud", None),
    # Ferretería (ampliación: electricidad, fontanería y pintura)
    ("Cable eléctrico", "Ferretería", "cable", "ud", "Rollo"),
    ("Interruptor", "Ferretería", "zap", "ud", None),
    ("Base de enchufe", "Ferretería", "plug-zap", "ud", None),
    ("Clavija", "Ferretería", "plug", "ud", None),
    ("Soldador de estaño", "Ferretería", "zap", "ud", None),
    ("Estaño para soldar", "Ferretería", "zap", "ud", None),
    ("Cola de contacto", "Ferretería", "droplet", "ud", None),
    ("Masilla", "Ferretería", "container", "ud", None),
    ("Cemento rápido", "Ferretería", "container", "ud", None),
    ("Yeso", "Ferretería", "container", "ud", None),
    ("Barniz", "Ferretería", "paint-bucket", "ud", None),
    ("Laca para madera", "Ferretería", "paint-bucket", "ud", None),
    ("Imprimación", "Ferretería", "paint-bucket", "ud", None),
    ("Silicona termofusible (barras)", "Ferretería", "zap", "pack", None),
    ("Pistola de silicona caliente", "Ferretería", "zap", "ud", None),
    ("Llaves Allen", "Ferretería", "wrench", "pack", None),
    ("Amoladora (radial)", "Ferretería", "drill", "ud", None),
    ("Sierra de calar", "Ferretería", "drill", "ud", None),
    ("Grifo (recambio)", "Ferretería", "droplet", "ud", None),
    ("Taladro eléctrico", "Ferretería", "drill", "ud", None),
    ("Brocas", "Ferretería", "drill", "pack", None),
    ("Nivel de burbuja", "Ferretería", "ruler", "ud", None),
    ("Rodillo de pintura", "Ferretería", "paint-roller", "ud", None),
    ("Brocha", "Ferretería", "paintbrush", "ud", None),
    ("Bandeja para pintura", "Ferretería", "paint-bucket", "ud", None),
    ("Pintura plástica", "Ferretería", "paint-bucket", "ud", None),
    ("Disolvente / aguarrás", "Ferretería", "droplet", "ud", None),
    ("Lija", "Ferretería", "layers", "pack", None),
    ("Casco de protección", "Ferretería", "hard-hat", "ud", None),
    ("Valla / malla metálica", "Ferretería", "fence", "ud", "Rollo"),
    ("Caja de herramientas", "Ferretería", "toolbox", "ud", None),
    ("Maletín de herramientas", "Ferretería", "tool-case", "ud", None),
    ("Silicona para juntas", "Ferretería", "droplet", "ud", None),
    # Papelería y Oficina (nueva categoría)
    ("Bolígrafos", "Papelería y Oficina", "pen", "pack", "10 ud"),
    ("Lápices", "Papelería y Oficina", "pencil", "pack", "12 ud"),
    ("Lápices de colores", "Papelería y Oficina", "palette", "pack", "12 ud"),
    ("Rotuladores fluorescentes", "Papelería y Oficina", "highlighter", "pack", None),
    ("Rotuladores punta fina", "Papelería y Oficina", "pen-line", "pack", "10 ud"),
    ("Rotuladores permanentes", "Papelería y Oficina", "pen-tool", "pack", None),
    ("Rotulador pizarra blanca", "Papelería y Oficina", "pen-tool", "ud", None),
    ("Goma de borrar", "Papelería y Oficina", "eraser", "ud", None),
    ("Sacapuntas", "Papelería y Oficina", "pencil", "ud", None),
    ("Portaminas", "Papelería y Oficina", "pen-tool", "ud", None),
    ("Minas de recambio", "Papelería y Oficina", "pen-tool", "pack", None),
    ("Corrector líquido", "Papelería y Oficina", "droplet", "ud", None),
    ("Pegamento de barra", "Papelería y Oficina", "package", "ud", None),
    ("Pegamento líquido / cola blanca", "Papelería y Oficina", "droplet", "ud", None),
    ("Cinta adhesiva transparente", "Papelería y Oficina", "layers", "ud", None),
    ("Cinta adhesiva de embalar", "Papelería y Oficina", "layers", "ud", None),
    ("Tijeras de oficina", "Papelería y Oficina", "scissors", "ud", None),
    ("Grapadora", "Papelería y Oficina", "square-stack", "ud", None),
    ("Grapas", "Papelería y Oficina", "square-stack", "ud", "Caja 1000"),
    ("Clips", "Papelería y Oficina", "paperclip", "ud", "Caja 100"),
    ("Pinzas binder", "Papelería y Oficina", "paperclip", "pack", None),
    ("Chinchetas", "Papelería y Oficina", "pin", "pack", None),
    ("Notas adhesivas (post-it)", "Papelería y Oficina", "sticky-note", "ud", "Bloc"),
    ("Bloc de notas", "Papelería y Oficina", "file-text", "ud", None),
    ("Cuaderno / libreta", "Papelería y Oficina", "notebook", "ud", None),
    ("Libreta de anillas", "Papelería y Oficina", "notebook-pen", "ud", None),
    ("Agenda", "Papelería y Oficina", "calendar-days", "ud", None),
    ("Folios A4", "Papelería y Oficina", "file", "pack", "500 hojas"),
    ("Cartulinas", "Papelería y Oficina", "files", "pack", None),
    ("Carpeta de anillas", "Papelería y Oficina", "folder", "ud", None),
    ("Carpeta de plástico", "Papelería y Oficina", "folder", "ud", None),
    ("Fundas / subcarpetas", "Papelería y Oficina", "files", "pack", None),
    ("Archivador", "Papelería y Oficina", "archive", "ud", None),
    ("Separadores de carpeta", "Papelería y Oficina", "layers", "pack", None),
    ("Sobres", "Papelería y Oficina", "file", "pack", None),
    ("Sellos de correos", "Papelería y Oficina", "stamp", "pack", None),
    ("Calculadora", "Papelería y Oficina", "calculator", "ud", None),
    ("Calculadora científica", "Papelería y Oficina", "calculator", "ud", None),
    ("Regla", "Papelería y Oficina", "ruler", "ud", None),
    ("Compás de dibujo", "Papelería y Oficina", "compass", "ud", None),
    ("Tinta para impresora", "Papelería y Oficina", "printer", "ud", "Cartucho"),
    ("Tóner impresora láser", "Papelería y Oficina", "printer", "ud", None),
    ("Papel fotográfico", "Papelería y Oficina", "image", "pack", None),
    ("Mochila escolar", "Papelería y Oficina", "backpack", "ud", None),
    ("Estuche escolar", "Papelería y Oficina", "briefcase", "ud", None),
    ("Plastilina", "Papelería y Oficina", "palette", "ud", None),
    ("Témperas", "Papelería y Oficina", "paint-bucket", "pack", None),
    ("Pinceles de manualidades", "Papelería y Oficina", "paintbrush", "pack", None),
    ("Etiquetas adhesivas", "Papelería y Oficina", "tags", "pack", None),
    ("Bolígrafo borrable", "Papelería y Oficina", "pen", "ud", None),
    ("Plastificadora", "Papelería y Oficina", "layers", "ud", None),
    ("Fundas para plastificar", "Papelería y Oficina", "layers", "pack", None),
    ("Guillotina de papel", "Papelería y Oficina", "scissors", "ud", None),
    ("Perforadora", "Papelería y Oficina", "circle-dot", "ud", None),
    ("Papel milimetrado", "Papelería y Oficina", "file", "pack", None),
    ("Transparencias para proyector", "Papelería y Oficina", "file", "pack", None),
    ("Tiza", "Papelería y Oficina", "pencil", "pack", None),
    ("Borrador de pizarra", "Papelería y Oficina", "eraser", "ud", None),
    ("Atlas / mapa mundi", "Papelería y Oficina", "globe", "ud", None),
    ("Diccionario", "Papelería y Oficina", "book", "ud", None),
    ("Cinta de doble cara", "Papelería y Oficina", "layers", "ud", None),
    ("Papel carbón", "Papelería y Oficina", "file", "pack", None),
    ("Cuadernos pentagramados", "Papelería y Oficina", "notebook", "ud", None),
    # Jardín y Terraza (nueva categoría)
    ("Tierra / sustrato universal", "Jardín y Terraza", "box", "ud", "Saco"),
    ("Abono / fertilizante", "Jardín y Terraza", "flask-conical", "ud", None),
    ("Semillas", "Jardín y Terraza", "sprout", "ud", "Sobre"),
    ("Macetas", "Jardín y Terraza", "flower-2", "ud", None),
    ("Regadera", "Jardín y Terraza", "droplet", "ud", None),
    ("Manguera de riego", "Jardín y Terraza", "droplet", "ud", None),
    ("Pala de jardín", "Jardín y Terraza", "shovel", "ud", None),
    ("Tijeras de podar", "Jardín y Terraza", "scissors", "ud", None),
    ("Guantes de jardinería", "Jardín y Terraza", "footprints", "pack", None),
    ("Malla antihierbas", "Jardín y Terraza", "layers", "ud", "Rollo"),
    ("Insecticida para plantas", "Jardín y Terraza", "droplet", "ud", None),
    ("Fungicida", "Jardín y Terraza", "droplet", "ud", None),
    ("Tutores para plantas", "Jardín y Terraza", "sprout", "pack", None),
    ("Césped artificial", "Jardín y Terraza", "layers", "ud", "Rollo"),
    ("Bandejas de semillero", "Jardín y Terraza", "sprout", "pack", None),
    ("Tijera eléctrica podar setos", "Jardín y Terraza", "scissors", "ud", None),
    ("Aspersor de riego", "Jardín y Terraza", "droplet", "ud", None),
    ("Programador de riego", "Jardín y Terraza", "droplet", "ud", None),
    ("Sustrato para cactus", "Jardín y Terraza", "box", "ud", "Saco"),
    ("Turba", "Jardín y Terraza", "box", "ud", "Saco"),
    ("Piedras decorativas", "Jardín y Terraza", "box", "ud", "Saco"),
    # Automóvil (nueva categoría)
    ("Aceite de motor", "Automóvil", "car-front", "ud", None),
    ("Líquido refrigerante", "Automóvil", "droplet", "ud", None),
    ("Líquido limpiaparabrisas", "Automóvil", "droplet", "ud", None),
    ("Líquido de frenos", "Automóvil", "droplet", "ud", None),
    ("Bombillas de coche", "Automóvil", "lightbulb", "ud", None),
    ("Escobillas limpiaparabrisas", "Automóvil", "wind", "ud", None),
    ("Fusibles de coche", "Automóvil", "zap", "pack", None),
    ("Cargador de batería (coche)", "Automóvil", "battery-charging", "ud", None),
    ("Kit de emergencia (triángulos/chaleco)", "Automóvil", "shield-check", "ud", None),
    # Limpieza (ampliación 2: revisado contra el surtido real de Mercadona,
    # sin nombres de marca)
    ("Detergente en cápsulas", "Limpieza", "washing-machine", "pack", None),
    ("Desinfectante para ropa", "Limpieza", "washing-machine", "ud", None),
    ("Antical para lavadora", "Limpieza", "washing-machine", "ud", None),
    ("Blanqueante ropa (oxígeno activo)", "Limpieza", "washing-machine", "ud", None),
    ("Limpiador de lavadora", "Limpieza", "washing-machine", "ud", None),
    ("Agua destilada", "Limpieza", "droplet", "ud", None),
    ("Agua para planchar", "Limpieza", "shirt", "ud", None),
    ("Limpiador de vitrocerámica", "Limpieza", "spray-can", "ud", None),
    ("Limpiador de muebles", "Limpieza", "spray-can", "ud", None),
    ("Limpiador de tapicerías y alfombras", "Limpieza", "spray-can", "ud", None),
    ("Alcohol de limpieza", "Limpieza", "droplet", "ud", None),
    ("Esponja mágica multiusos", "Limpieza", "sparkles", "pack", None),
    ("Insecticida para cucarachas y hormigas", "Limpieza", "bug-off", "ud", None),
    ("Antimosquitos eléctrico (recambio)", "Limpieza", "bug-off", "ud", None),
    ("Antipolillas", "Limpieza", "bug-off", "ud", None),
    ("Trampa para cucarachas", "Limpieza", "bug", "ud", None),
    ("Espiral antimosquitos", "Limpieza", "bug-off", "pack", None),
    ("Raticida", "Limpieza", "rat", "ud", None),
    ("Absorbeolores para nevera", "Limpieza", "refrigerator", "ud", None),
    ("Antihumedad para armarios", "Limpieza", "droplets", "ud", None),
    ("Moldes de aluminio para horno", "Limpieza", "package-2", "ud", None),
    ("Recipientes herméticos de cocina", "Limpieza", "container", "ud", None),
    ("Bolsa isotérmica", "Limpieza", "container", "ud", None),
    ("Palillos de dientes", "Limpieza", "utensils", "pack", None),
    ("Carbón vegetal para barbacoa", "Limpieza", "flame", "ud", "Saco"),
    ("Pastillas para encender fuego", "Limpieza", "flame", "pack", None),
    # Higiene (ampliación 2)
    ("Pasta de dientes infantil", "Higiene", "smile", "ud", None),
    ("Cepillos interdentales", "Higiene", "smile", "pack", None),
    ("Cabezales de recambio para cepillo eléctrico", "Higiene", "smile", "pack", None),
    ("Cepillo de dientes eléctrico", "Higiene", "battery-charging", "ud", None),
    ("Fijador para dentadura postiza", "Higiene", "smile", "ud", None),
    ("Pastillas limpiadoras de dentadura postiza", "Higiene", "smile", "pack", None),
    ("Spray bucal refrescante", "Higiene", "spray-can", "ud", None),
    ("Aceite corporal", "Higiene", "droplet", "ud", None),
    ("Exfoliante corporal", "Higiene", "sparkles", "ud", None),
    ("Crema para pies", "Higiene", "footprints", "ud", None),
    ("Papel higiénico húmedo", "Higiene", "droplet", "pack", None),
    ("Toallitas hidroalcohólicas", "Higiene", "spray-can", "pack", None),
    ("Bandas de cera depilatoria", "Higiene", "sparkles", "pack", None),
    ("Crema depilatoria", "Higiene", "spray-can", "ud", None),
    ("Pinzas de depilar", "Higiene", "scissors", "ud", None),
    # Snacks y Dulces (ampliación 2)
    ("Cortezas de cerdo", "Snacks y Dulces", "sandwich", "pack", None),
    ("Snack horneado de legumbres", "Snacks y Dulces", "salad", "pack", None),
]

# Configuración OAuth para Google y Apple
# Obtén estas credenciales en:
# - Google: https://console.cloud.google.com/
# - Apple: https://developer.apple.com/
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID", "")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET", "")
APPLE_CLIENT_ID = os.getenv("APPLE_CLIENT_ID", "")
APPLE_CLIENT_SECRET = os.getenv("APPLE_CLIENT_SECRET", "")
APPLE_TEAM_ID = os.getenv("APPLE_TEAM_ID", "")

# Configuración de Email (para invitaciones a compartir listas)
SMTP_SERVER = os.getenv("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
SMTP_FROM = os.getenv("SMTP_FROM", "noreply@homestock.local")
APP_URL = os.getenv("APP_URL", "http://localhost:5000")
# Dominio publico (sin esquema) mostrado en las paginas legales. Se deriva de
# APP_URL para que baste con cambiar esa variable desde el Panel de Gestion
# del Servidor si la app cambia de dominio, sin tocar codigo.
DOMINIO_PUBLICO = APP_URL.split("://", 1)[-1]

# Identidad del responsable del tratamiento (Aviso Legal / RGPD-LOPDGDD):
# persona fisica, sin entidad mercantil detras de la app.
TITULAR_LEGAL = "Alejandro Paz Silva"
EMAIL_CONTACTO_LEGAL = "pazsilva.alejandro@gmail.com"

# Version vigente de Terminos y Condiciones / Politica de Privacidad. Al
# subir esta fecha, todo usuario (incluido el que ya tenia cuenta) debe
# volver a aceptar antes de seguir usando la app (ver rutas/auth.py).
VERSION_TERMINOS = "2026-08-04-2"
