// GENERADO — no editar a mano.
//
// Copia del idioma por defecto (es) de stockhogar/translations.json, usada como
// estado inicial de TranslationContext. Sin ella, el HTML del servidor y el
// primer pintado salen con las CLAVES en crudo ("titulo_login",
// "btn_iniciar_sesion"...) hasta que /api/idiomas/todos/<idioma> responde: el
// usuario veia las claves y React tiraba el HTML del servidor con un error de
// hidratacion (#418) en todas las paginas.
//
// Regenerar con:
//   python scripts/generar_traducciones_base.py
// tests/test_traducciones_completas.py falla si este fichero se desincroniza.

const TRADUCCIONES_BASE: Record<string, string> = {
  "abriendo_whatsapp": "Abriendo WhatsApp...",
  "abriendo_whatsapp_numero": "Abriendo WhatsApp con el número...",
  "abrir_whatsapp": "Abrir WhatsApp",
  "acceso_revocado": "Acceso revocado",
  "acciones_gastos": "Más acciones",
  "acepta_terminos_texto": "He leído y acepto los Términos y Condiciones y la Política de Privacidad",
  "aceptando_invitacion": "Aceptando invitación...",
  "activado": "Activado",
  "activo": "Activo",
  "agrupado": "Agrupado",
  "agrupar_por_categoria": "Agrupar por categoría",
  "ajustes": "Ajustes",
  "ajustes_lista": "Ajustes de la lista",
  "algo_salio_mal": "Algo salió mal",
  "alternativas": "Alternativas",
  "anadir_a_la_lista": "Añadir a la lista",
  "anadir_ingrediente": "Añadir ingrediente",
  "analizando_ticket_ocr": "Analizando ticket (OCR)... puede tardar un poco",
  "analizar": "Analizar",
  "app_descripcion": "Gestiona tu inventario del hogar y lista de compra de forma inteligente",
  "app_name": "📦 Dreame!",
  "aria_activar_modo_oscuro": "Activar modo oscuro",
  "aria_cancelar_edicion": "Cancelar edición",
  "aria_confirmar_eliminacion": "Confirmar eliminación",
  "aria_desactivar_modo_oscuro": "Desactivar modo oscuro",
  "aria_excluir_producto": "Excluir producto",
  "aria_filtrar_bajo_stock": "Filtrar por bajo stock",
  "aria_filtrar_revisar_caducidad": "Filtrar por revisar caducidad",
  "aria_idioma_interfaz": "Idioma de la interfaz",
  "aria_incluir_producto": "Incluir producto",
  "aria_marcar_comprado_producto": "Marcar {nombre} como comprado",
  "aria_quitar_acceso": "Quitar acceso",
  "aria_quitar_filtro_bajo_stock": "Quitar filtro de bajo stock",
  "aria_quitar_filtro_caducidad": "Quitar filtro de caducidad",
  "aria_renombrar_hogar": "Renombrar hogar {nombre}",
  "aria_restar_uno": "Restar uno",
  "aria_restaurar_producto": "Restaurar {nombre}",
  "aria_sumar_uno": "Sumar uno",
  "aria_ver_todos_articulos": "Ver todos los artículos",
  "articulo": "Artículo",
  "articulos": "Artículos",
  "articulos_pendientes": "artículos pendientes",
  "aviso_motor_ocr_degradado": "El motor de reconocimiento en la nube no está disponible en este servidor: los tickets se leen solo con reconocimiento local, bastante menos preciso.",
  "aviso_tema_hogar_cambiado": "El estilo de este hogar ha cambiado",
  "aviso_tema_hogar_cambiado_con_nombre": "{nombre} ha cambiado el estilo de este hogar",
  "ayuda_borrar_categoria": "Toca la ✕ de una categoría para borrarla (solo si no la usa ningún producto).",
  "ayuda_diagnostico_1": "Asegúrate que el backend Flask está corriendo (ver run.py)",
  "ayuda_diagnostico_2": "Verifica la variable de entorno NEXT_PUBLIC_API_URL en .env.local",
  "ayuda_diagnostico_3": "Las peticiones van por el proxy de Next (next.config.mjs rewrites), no directas al navegador",
  "ayuda_diagnostico_4": "Consulta el archivo SETUP.md para más información",
  "ayuda_lista_catalogo": "Toca un producto para añadirlo. Mantén pulsado para ajustar cantidad, unidad, sub-descripción o icono antes de añadirlo.",
  "ayuda_stock_catalogo": "Toca un producto para indicar su cantidad y añadirlo al stock.",
  "ayuda_whatsapp": "Sin teléfono: abre WhatsApp Web. Con teléfono: envía un mensaje directo.",
  "añadido_a_la_compra": "Añadido a la compra",
  "añadiendo": "Añadiendo...",
  "añadir": "Añadir",
  "añadir_a_la_compra": "Añadir a la compra",
  "añadir_a_la_lista": "Añadir a la lista",
  "añadir_a_lista": "Añadir a lista",
  "añadir_a_lista_compra": "Añadir a la lista de la compra",
  "añadir_al_stock": "Añadir al stock",
  "añadir_articulo": "Añadir Artículo",
  "añadir_linea": "+ Añadir línea",
  "añadir_primer_producto": "Añadir el Primer Producto",
  "añadir_producto": "Añadir Producto",
  "añadir_todos": "Añadir todos",
  "añadir_usuario": "Añadir usuario",
  "añadir_x": "Añadir \"{nombre}\"",
  "añadir_x_al_stock": "Añadir \"{nombre}\" al stock",
  "backend_accesible": "Backend accesible a través del proxy de Next",
  "backend_flask_check": "Backend Flask (/)",
  "backend_no_conecta": "No se puede conectar al backend",
  "bajo_minimo": "Bajo mínimo",
  "bajo_stock": "bajo stock",
  "balance_por_persona": "Balance por persona",
  "balances": "Balances",
  "banner_crear_lista_texto": "⚠️ Debes crear una lista para comenzar.",
  "borrar": "Borrar",
  "borrar_categoria_titulo": "Borrar categoría",
  "btn_aceptar": "Aceptar",
  "btn_acepto_continuar": "He leído y acepto, continuar",
  "btn_cambiar_password": "Cambiar Contraseña",
  "btn_cerrar_otras_sesiones": "Cerrar sesión en otros dispositivos",
  "btn_enviar_enlace_reset": "Enviar enlace",
  "btn_exportar_mis_datos": "Descargar mis datos",
  "btn_iniciar_sesion": "Iniciar Sesión",
  "btn_rechazar": "Rechazar",
  "btn_registrarse": "Registrarse",
  "btn_restablecer_password": "Restablecer contraseña",
  "btn_verificar_codigo": "Verificar",
  "btn_verificar_email": "Verificar email",
  "buscar_en_catalogo": "Buscar artículo...",
  "buscar_generico": "Buscar...",
  "buscar_icono": "Buscar icono... (ej. leche, lim)",
  "buscar_icono_simple": "Buscar icono...",
  "buscar_producto": "Buscar producto...",
  "caducados": "caducados",
  "cambiando": "Cambiando...",
  "cambiar_foto": "Cambiar foto",
  "cambiar_icono": "Cambiar icono",
  "cambiar_idioma": "Cambiar idioma",
  "cambiar_lista": "Cambiar lista",
  "cambios_guardados_correctamente": "Cambios guardados correctamente",
  "cancelar": "Cancelar",
  "cantidad": "Cantidad",
  "cargando": "Cargando...",
  "cargando_hogares": "Cargando hogares...",
  "cargando_inventario": "Cargando inventario...",
  "cargando_lista_compra": "Cargando lista de compra...",
  "cargando_miembros": "Cargando miembros...",
  "cargar": "Cargar",
  "catalogo_aprendido": "Catálogo aprendido",
  "catalogo_sin_coincidencias": "Ningún artículo coincide con la búsqueda",
  "categoria": "Categoría",
  "categoria_alimentacion": "Alimentación",
  "categoria_bebe": "Bebé",
  "categoria_bebidas": "Bebidas",
  "categoria_carnes_y_embutidos": "Carnes y Embutidos",
  "categoria_cereales_y_pasta": "Cereales y Pasta",
  "categoria_congelados": "Congelados",
  "categoria_despensa": "Despensa",
  "categoria_farmacia_y_botiquin": "Farmacia y Botiquín",
  "categoria_frutas_y_verduras": "Frutas y Verduras",
  "categoria_higiene": "Higiene",
  "categoria_hogar": "Hogar",
  "categoria_lacteos_y_huevos": "Lácteos y Huevos",
  "categoria_limpieza": "Limpieza",
  "categoria_mascotas": "Mascotas",
  "categoria_otros": "Otros",
  "categoria_panaderia_y_bolleria": "Panadería y Bollería",
  "categoria_pescados_y_mariscos": "Pescados y Mariscos",
  "categoria_snacks_y_dulces": "Snacks y Dulces",
  "categorias": "Categorías",
  "categorias_gasto": "Categorías de gasto",
  "cerrar_notificacion": "Cerrar notificación",
  "cerrar_sesion": "Cerrar sesión",
  "cerrar_sesion_titulo": "Cerrar Sesión",
  "codigo_no_reconocido": "Codigo no reconocido. Escribe el nombre del articulo y se recordara para la proxima vez.",
  "codigo_reenviado": "Código reenviado correctamente",
  "color": "Color",
  "color_lista": "Color de la lista",
  "compartida_puede_comprar": "Puedes marcar comprado",
  "compartida_puedes_editar": "Puedes editar",
  "compartida_solo_ver": "Solo puedes ver",
  "compartido": "Compartido",
  "compartido_puedes_editar": "Compartido (puedes editar)",
  "compartido_solo_ver": "Compartido (solo ver)",
  "compartidos_conmigo": "Compartidos conmigo",
  "compartir": "Compartir",
  "compartir_con": "📤 Compartir con...",
  "compartir_con_usuario": "Compartir con Usuario",
  "compartir_hogar": "Compartir hogar",
  "compartir_lista_titulo": "Lista de la compra",
  "compartir_whatsapp": "Compartir por WhatsApp",
  "completado": "Completado",
  "comprado": "Comprado",
  "comprados_contador": "Comprados",
  "comprados_recientemente": "Comprados recientemente",
  "comprobando": "Comprobando...",
  "con_acceso": "Con acceso",
  "concepto_placeholder": "¿En qué se ha gastado?",
  "confianza": "Confianza",
  "configuracion": "⚙️ Configuración",
  "confirma_contrasena": "Confirma contraseña",
  "confirmar": "Confirmar",
  "confirmar_borrar": "¿Estás seguro de que quieres borrar este producto?",
  "confirmar_borrar_articulo_lista": "¿Borrar este artículo de la lista?",
  "confirmar_borrar_categoria": "¿Borrar la categoría \"{nombre}\"?",
  "confirmar_cerrar_sesion_pregunta": "¿Seguro que quieres cerrar sesión?",
  "confirmar_e_importar_stock": "Confirmar e importar al stock",
  "confirmar_eliminar_cuenta_pregunta": "¿Estás seguro? Esta acción no puede deshacerse. Se eliminarán todos tus datos.",
  "confirmar_eliminar_gasto": "¿Eliminar este gasto?",
  "confirmar_eliminar_hogar": "¿Estás seguro de que deseas eliminar este hogar?",
  "confirmar_eliminar_producto_stock": "¿Eliminar este producto del stock?",
  "confirmar_items": "Confirmar items",
  "confirmar_nueva_password": "Confirmar Nueva Contraseña",
  "confirmar_revocar_acceso": "¿Estás seguro de que deseas revocar el acceso?",
  "confirmar_salir_hogar": "¿Estás seguro de que deseas salir de este hogar?",
  "confirmar_salir_lista": "¿Estás seguro de que deseas salir de esta lista?",
  "conocido": "Conocido",
  "consumo": "Consumo",
  "continuar_apple": "Continuar con Apple",
  "continuar_google": "Continuar con Google",
  "contraseña": "Contraseña",
  "copiar": "📋 Copiar",
  "copiar_enlace": "Copiar enlace",
  "copiar_logs": "Copiar logs",
  "correo_electronico": "Correo Electrónico",
  "crea_una": "Crea una",
  "crear": "Crear",
  "crear_cuenta": "Crear cuenta",
  "crear_hogar_nuevo": "Crear un Hogar nuevo",
  "crear_lista": "Crear lista",
  "crear_lista_ahora": "Crear lista ahora",
  "crear_nueva_lista_titulo": "Crear nueva lista",
  "crear_primera_compra": "Crear Mi Primera Compra",
  "crear_y_entrar": "Crear y entrar",
  "de_presupuesto": "de",
  "debe": "Debe",
  "debes_total": "Debes en total",
  "del_total": "del total",
  "desactivado": "Desactivado",
  "descripcion": "Descripción",
  "descripcion_catalogo_aprendido": "Artículos que la app recuerda (icono, categoría, unidad habitual) para sugerirlos automáticamente.",
  "descripcion_mis_articulos_personalizados": "Artículos que has creado tú para tu hogar. Puedes eliminarlos si ya no los usas.",
  "desde": "Desde",
  "deseleccionar_todos": "Deseleccionar todos",
  "deshacer": "Deshacer",
  "detalle_asegurate_flask": "Asegúrate que Flask está corriendo (ver run.py) y que NEXT_PUBLIC_API_URL apunta ahí.",
  "detalle_next_public_url": "NEXT_PUBLIC_API_URL: {valor}",
  "detalle_status": "Status: {status}",
  "deudas_saldadas": "Cuentas saldadas",
  "diagnostico_completado": "Diagnóstico completado",
  "diagnostico_integracion_subtitulo": "Verifica la conectividad entre el frontend y el backend",
  "diagnostico_integracion_titulo": "Diagnóstico de Integración",
  "dias_sin_actualizar_para_avisar": "Días sin actualizar para avisar",
  "digitos": "dígitos",
  "dividir_partes_iguales": "Dividir a partes iguales",
  "dividir_personalizado": "Personalizado",
  "dividir_por_partes": "Por partes",
  "dividir_por_porcentaje": "Por porcentaje",
  "doble_factor_descripcion": "Al iniciar sesión, además de la contraseña te pediremos un código enviado a tu email.",
  "doble_factor_titulo": "Verificación en dos pasos",
  "edicion_avanzada_articulo": "Edición avanzada para artículo personalizado ID {id}. Esta funcionalidad puede extenderse en el futuro.",
  "editar": "Editar",
  "editar_articulo": "Editar artículo",
  "editar_gasto": "Editar gasto",
  "editar_lista": "Editar lista",
  "editar_producto": "Editar producto",
  "editar_receta": "Editar receta",
  "ej_bolsas_basura": "Ej. Bolsas de basura",
  "ej_entera": "Ej. Entera",
  "ej_mi_inventario": "Ej. Mi inventario",
  "ej_mi_lista_compra": "Ej. Mi lista de compra",
  "ej_papel_higienico": "Ej. Papel higiénico",
  "elegir_del_catalogo": "Elegir del catálogo",
  "elegir_icono": "Elegir icono",
  "elegir_orden_articulos": "Elige cómo deseas ordenar los artículos:",
  "elige_un_hogar": "Elige un Hogar",
  "eliminando": "Eliminando...",
  "eliminar": "Eliminar",
  "eliminar_cuenta_titulo": "Eliminar Cuenta",
  "eliminar_hogar": "Eliminar hogar",
  "eliminar_pregunta": "¿Eliminar?",
  "eliminar_receta_confirmar": "¿Eliminar esta receta?",
  "email": "Email",
  "email_asunto_invitacion_hogar": "Te invito al hogar: {nombre}",
  "email_cuerpo_invitacion_hogar": "Hola! Quiero compartir mi hogar \"{nombre}\" contigo.\n\nHaz clic aquí para aceptar:\n{enlace}",
  "email_destinatario": "Email del destinatario",
  "email_no_verificado_aviso": "Tu email no está verificado.",
  "email_verificado_ok": "¡Tu email ha sido verificado!",
  "en_listas_compra_y_stock": "En listas de compra y stock",
  "enlace": "Enlace",
  "enlace_aviso_legal": "Aviso Legal",
  "enlace_compartible_titulo": "Enlace compartible",
  "enlace_cookies": "Política de Cookies",
  "enlace_copiado_portapapeles": "¡Enlace copiado al portapapeles!",
  "enlace_generado_copia_comparte": "Enlace generado - cópialo y comparte!",
  "enlace_generado_titulo": "🔗 Enlace de invitación generado:",
  "enlace_invitacion_generado": "¡Enlace de invitación generado!",
  "enlace_privacidad": "Política de Privacidad",
  "enlace_terminos": "Términos y Condiciones",
  "enlace_valido_7_dias": "✓ Válido por 7 días. Comparte por WhatsApp, email, mensaje directo, etc.",
  "entrando": "Entrando...",
  "entrar": "Entrar",
  "entre_2_y_50_caracteres": "Entre 2 y 50 caracteres",
  "err_aceptar_invitacion_generico": "Error al aceptar invitación: {error}",
  "err_actualizar": "Error al actualizar",
  "err_actualizar_cantidad": "Error al actualizar cantidad",
  "err_actualizar_nombre": "Error al actualizar el nombre",
  "err_actualizar_nombre_mostrar": "Error al actualizar el nombre",
  "err_anadir_articulo": "Error al añadir artículo",
  "err_archivo_demasiado_grande": "El archivo es demasiado grande (máximo 20 MB).",
  "err_archivo_muy_grande": "Archivo demasiado grande (máx {mb}MB)",
  "err_archivo_vacio": "Archivo vacío",
  "err_articulo_personalizado_duplicado": "Ya tienes un artículo con ese nombre",
  "err_camara_no_disponible": "No se pudo acceder a la camara.",
  "err_cambiar_idioma": "Error al cambiar el idioma",
  "err_cambiar_password": "Error al cambiar la contraseña",
  "err_campos_obligatorios": "Todos los campos son obligatorios",
  "err_campos_requeridos": "Por favor completa todos los campos",
  "err_cargar_historial_precios": "No se pudo cargar el historial de precios.",
  "err_cargar_hogares": "No se han podido cargar tus hogares",
  "err_categoria_duplicada": "Ya existe una categoría con ese nombre",
  "err_categoria_en_uso": "Hay {en_uso} producto(s) usando esta categoría. Cámbialos antes de borrarla.",
  "err_categoria_gasto_en_uso": "Hay {en_uso} gasto(s) usando esta categoría. Cámbialos antes de borrarla.",
  "err_cerrar_sesion": "Error al cerrar sesión",
  "err_claves_debe_ser_lista": "claves debe ser una lista",
  "err_codigo_expirado": "El código ha caducado. Pide uno nuevo.",
  "err_codigo_incorrecto": "Código incorrecto.",
  "err_codigo_no_reconocido": "Código de barras no reconocido",
  "err_compartir": "Error al compartir",
  "err_conexion_servidor": "Error de conexión con el servidor",
  "err_copiar_enlace": "Error al copiar el enlace",
  "err_crear_categoria": "Error al crear la categoría",
  "err_debe_aceptar_terminos": "Debes aceptar los Términos y Condiciones y la Política de Privacidad para continuar",
  "err_demasiadas_peticiones": "Demasiadas peticiones. Espera un momento antes de volver a intentarlo.",
  "err_demasiados_intentos_2fa": "Demasiados intentos con el código. Prueba de nuevo más tarde",
  "err_demasiados_intentos_login": "Demasiados intentos fallidos. Espera unos minutos antes de volver a intentarlo.",
  "err_demasiados_reenvios_2fa": "Has pedido el código demasiadas veces. Prueba de nuevo más tarde",
  "err_doble_factor_requiere_email": "Necesitas un email en tu cuenta para activar la verificación en dos pasos.",
  "err_editar_articulo": "Error al editar el artículo",
  "err_eliminar_articulo": "Error al eliminar",
  "err_eliminar_articulo_personalizado": "Error al eliminar el artículo",
  "err_eliminar_articulo_personalizado_en_uso": "No se puede eliminar: está en uso en la lista de la compra",
  "err_eliminar_categoria_uso": "Error al eliminar la categoría (puede estar en uso)",
  "err_eliminar_cuenta": "Error al eliminar la cuenta",
  "err_eliminar_hogar": "Error al eliminar el hogar",
  "err_eliminar_producto": "Error al eliminar producto",
  "err_eliminar_receta": "No se pudo eliminar la receta.",
  "err_email_invalido": "El correo electrónico no es válido",
  "err_email_no_configurado": "Tu cuenta no tiene un email configurado.",
  "err_email_no_disponible": "Ese correo electrónico no está disponible",
  "err_email_ya_verificado": "Tu email ya está verificado.",
  "err_error_al_actualizar_permiso": "Error al actualizar el permiso",
  "err_error_al_buscar": "Error al buscar",
  "err_error_al_cargar_miembros": "Error al cargar miembros",
  "err_error_al_crear_hogar": "Error al crear el hogar",
  "err_error_al_guardar": "Error al guardar",
  "err_error_al_revocar_acceso": "Error al revocar el acceso",
  "err_error_al_salir_hogar": "Error al salir del hogar",
  "err_falta_email_o_usuario": "Debe proporcionar email o nombre de usuario",
  "err_formato_no_permitido": "Formato no permitido. Usa PNG, JPG, etc.",
  "err_generar_enlace": "Error al generar enlace",
  "err_guardar_cambios": "Error al guardar cambios",
  "err_guardar_presupuesto": "No se pudo guardar el presupuesto.",
  "err_guardar_receta": "No se pudo guardar la receta.",
  "err_importando_productos": "Error importando los productos",
  "err_importar_csv": "No se pudo importar el fichero.",
  "err_importe_no_cuadra": "La suma del reparto no coincide con el importe total",
  "err_interno_generico": "Ha ocurrido un error interno. Inténtalo de nuevo o contacta con soporte.",
  "err_invitacion_expirada": "La invitación ha expirado",
  "err_invitacion_no_encontrada": "Invitación no encontrada o expirada",
  "err_invitacion_usada": "Esta invitación ya ha sido usada",
  "err_limite_hogares": "Has alcanzado el número máximo de hogares que puedes crear",
  "err_limite_invitaciones_diario": "Este hogar ha alcanzado el limite diario de invitaciones enviadas",
  "err_limite_ocr_diario": "Has alcanzado el límite diario de escaneos de tickets",
  "err_limite_recibos_diario": "Has alcanzado el limite diario de fotos de recibo",
  "err_min_2_caracteres": "Ingresa al menos 2 caracteres",
  "err_nada_que_actualizar": "No hay nada que actualizar",
  "err_nivel_invalido": "Nivel debe ser 'ver' o 'editar'",
  "err_no_autenticado": "No has iniciado sesión",
  "err_no_borrar_categoria_defecto": "No se puede borrar la categoría \"{nombre}\"",
  "err_no_cambiar_permiso_propietario": "No puedes cambiar el permiso del propietario",
  "err_no_detecto_producto_imagen": "No se detectó ningún producto en la imagen. Prueba con una foto más nítida y bien encuadrada.",
  "err_no_hay_hogar_activo": "No hay una lista activa",
  "err_no_hay_lista_seleccionada": "Error: No hay lista seleccionada",
  "err_no_permitido": "No tienes permiso para esta acción",
  "err_no_revocar_acceso_propietario": "No puedes revocar el acceso del propietario",
  "err_no_salir_propio_hogar": "No puedes salir de tu propia lista",
  "err_no_se_pudo_crear_lista": "No se pudo crear la lista. Comprueba tu conexión.",
  "err_no_se_pudo_guardar_cambios": "No se pudo guardar los cambios. Comprueba tu conexión.",
  "err_no_se_pudo_salir_lista": "No se pudo salir de la lista. Comprueba tu conexión.",
  "err_nombre_lista_requerido": "El nombre de la lista es requerido",
  "err_nombre_max_80": "El nombre no puede exceder 80 caracteres",
  "err_nombre_obligatorio": "El nombre es obligatorio",
  "err_nombre_usuario_vacio": "El nombre de usuario no puede estar vacío",
  "err_nombre_vacio": "El nombre no puede estar vacío",
  "err_nueva_password_min_4": "La nueva contraseña debe tener al menos 4 caracteres",
  "err_nueva_password_min_8": "La nueva contraseña debe tener al menos 10 caracteres",
  "err_oauth_apple_fallo": "No se pudo completar el inicio de sesión con Apple. Inténtalo de nuevo.",
  "err_oauth_apple_generico": "Error de Apple: {error}",
  "err_oauth_apple_identidad": "No se pudo verificar la identidad de Apple.",
  "err_oauth_google_fallo": "No se pudo completar el inicio de sesión con Google. Inténtalo de nuevo.",
  "err_oauth_google_generico": "Error de Google: {error}",
  "err_oauth_sin_codigo": "No se recibió código de autorización",
  "err_oauth_solicitud_invalida": "Solicitud de autenticación inválida o expirada",
  "err_password_actual_incorrecta": "La contraseña actual es incorrecta",
  "err_password_filtrada": "Esta contraseña ha aparecido en filtraciones de datos conocidas. Elige otra.",
  "err_password_igual_anterior": "La nueva contraseña debe ser distinta de la actual",
  "err_password_min_4": "La contraseña debe tener mínimo 4 caracteres",
  "err_password_min_8": "La contraseña debe tener al menos 10 caracteres",
  "err_procesando_ticket": "Error procesando ticket",
  "err_recurso_no_encontrado": "{recurso} no encontrado",
  "err_registro_cerrado": "El registro de nuevas cuentas está cerrado temporalmente",
  "err_renombrar_hogar": "Error al renombrar el hogar",
  "err_seleccionar_hogar": "Error al seleccionar el hogar",
  "err_seleccionar_pagador": "Indica quién pagó el gasto",
  "err_sesion_no_confirmada": "No se pudo confirmar la sesión iniciada",
  "err_sin_archivo": "No se envió archivo",
  "err_sin_fichero": "No se ha recibido ningun fichero",
  "err_sin_imagen": "No se ha recibido ninguna imagen",
  "err_sin_participantes": "Selecciona al menos un participante",
  "err_sin_permiso_editar_hogar": "No tienes permisos para editar esta lista",
  "err_suscripcion_push_invalida": "Suscripcion push invalida",
  "err_tesseract_no_disponible": "No se pudo leer la imagen. Comprueba que Tesseract está instalado. Detalle: {detalle}",
  "err_token_expirado": "Este enlace ha caducado.",
  "err_token_invalido": "Este enlace no es válido.",
  "err_token_usado": "Este enlace ya se ha utilizado.",
  "err_ultimo_usuario": "No puedes borrar el único usuario que queda",
  "err_usa_cambiar_password": "Para cambiar la contraseña usa la opción de cambio de contraseña",
  "err_usuario_duplicado": "Ya existe un usuario con ese nombre",
  "err_usuario_no_encontrado": "Usuario no encontrado",
  "err_usuario_no_es_miembro": "Ese usuario ya no es miembro del hogar",
  "error": "Error",
  "error_borrar_categoria": "No se pudo borrar la categoría. Inténtalo de nuevo.",
  "error_cargar_categorias": "No se pudieron cargar las categorías. Comprueba tu conexión.",
  "error_conexion_titulo": "Error de conexión",
  "error_consultando_estado": "Error consultando el estado",
  "error_contrasenas_no_coinciden": "Las contraseñas no coinciden",
  "error_crear_hogar": "Error al crear el hogar",
  "error_credenciales_incorrectas": "Usuario o contraseña incorrectos",
  "error_entrar_hogar": "Error al entrar en el hogar",
  "error_no_se_pudo_aceptar_invitacion": "No se pudo aceptar la invitación",
  "error_no_se_pudo_crear_cuenta": "No se pudo crear la cuenta",
  "error_no_se_pudo_procesar_invitacion": "No se pudo procesar la invitación",
  "error_obteniendo_token": "Error obteniendo el token",
  "error_procesar": "Error al procesar el ticket",
  "escanear_codigo_barras": "Escanear codigo de barras",
  "escanear_ticket": "📷 Escanear ticket",
  "escanear_ticket_simple": "Escanear ticket",
  "escaner_no_soportado": "Tu navegador no permite escanear codigos de barras. Escribe el nombre del articulo a mano.",
  "estadisticas": "Estadísticas",
  "estas_en_paz": "Estás en paz",
  "este_campo_es_requerido": "Este campo es requerido",
  "evolucion_consumo": "Evolución de consumo",
  "evolucion_mensual": "Evolución mensual",
  "excluido": "Excluido",
  "exportar_csv": "Exportar CSV",
  "fecha": "Fecha",
  "fecha_fin_opcional": "Fecha de fin (opcional)",
  "fecha_gasto": "Fecha",
  "fecha_inicio": "Fecha de inicio",
  "filtros": "Filtros",
  "footer_copyright": "© 2026 Todos los derechos reservados",
  "formato_invalido": "Formato inválido",
  "frecuencia": "Frecuencia",
  "frecuencia_anual": "Anual",
  "frecuencia_mensual": "Mensual",
  "frecuencia_semanal": "Semanal",
  "gasto": "Gasto",
  "gasto_recurrente": "Gasto recurrente",
  "gasto_total_por_categoria": "Gasto total por categoría",
  "gastos_recurrentes": "Gastos recurrentes",
  "generando": "Generando...",
  "generar_enlace_compartible": "Generar Enlace Compartible",
  "generar_enlace_invitacion": "Generar Enlace de Invitación",
  "gestionar_categorias_gasto": "Gestionar categorías de gasto",
  "grid": "Grid",
  "guardando": "Guardando...",
  "guardar": "Guardar",
  "guardar_cambios": "Guardar cambios",
  "hacer_foto_boton": "Hacer foto",
  "has_salido_de_la_lista": "Has salido de la lista",
  "hasta": "Hasta",
  "historial": "Historial",
  "historial_consumo": "Historial de consumo",
  "historial_pagos": "Historial de pagos",
  "historial_precios": "Historial de precios",
  "hogar": "Hogar",
  "icono": "Icono",
  "icono_dospuntos": "Icono:",
  "idioma": "Idioma",
  "idioma_sistema": "Idioma del sistema",
  "importar_csv": "Importar CSV",
  "importe": "Importe",
  "importe_participante": "Importe participante",
  "importe_total": "Importe total",
  "ingredientes": "Ingredientes",
  "ingredientes_anadidos_a_la_lista": "Ingredientes añadidos a la lista de la compra",
  "ingresa_email_valido": "Ingresa un email válido",
  "ingresar": "Ingresar",
  "inicia_sesion_link": "Inicia sesión",
  "iniciando_diagnostico": "Iniciando diagnóstico...",
  "inicio_sesion": "Inicio de sesión",
  "instalar_app": "Instalar app",
  "instalar_app_texto": "Instala esta app en tu dispositivo para acceder más rápido y usarla sin conexión.",
  "intentar_nuevamente": "Intentar nuevamente",
  "invitacion_aceptada_texto": "Ya tienes acceso a la lista compartida.",
  "invitacion_aceptada_titulo": "¡Invitación aceptada!",
  "invitacion_rechazada_ok": "Invitación rechazada.",
  "invitaciones_pendientes_titulo": "Invitaciones pendientes",
  "ir_a_iniciar_sesion": "Volver a iniciar sesión",
  "ir_a_la_app": "Ir a la app",
  "ir_a_la_lista": "Ir a la lista",
  "ir_al_dashboard": "Ir al Dashboard",
  "items_añadidos": "Items añadidos correctamente",
  "items_encontrados": "Items encontrados",
  "jpg_png_hasta_10mb": "JPG, PNG o PDF, hasta 10 MB",
  "le_deben": "Le deben",
  "leyendo_ticket": "Leyendo el ticket, un momento...",
  "limpiar_busqueda": "Limpiar búsqueda",
  "limpiar_filtros": "Limpiar filtros",
  "liquidacion": "Liquidación",
  "lista_actualizada_correctamente": "Lista actualizada correctamente",
  "lista_compartida_correctamente": "¡Lista compartida correctamente!",
  "lista_compra": "🛒 Lista de la compra",
  "lista_compra_check": "Lista de la compra (/api/articulos)",
  "lista_vacia": "Tu lista de la compra está vacía. Toca \"+\" para añadir algo.",
  "listas": "Listas",
  "listo": "Listo",
  "log_backend_accesible": "✓ Backend accesible",
  "log_backend_respondio": "✗ Backend respondió {status}",
  "log_csrf_fallido": "✗ CSRF token fallido",
  "log_csrf_ok": "✓ CSRF token OK",
  "log_endpoint_articulos": "✓ Endpoint de artículos respondiendo",
  "log_endpoint_estado": "✓ Endpoint de estado respondiendo",
  "log_endpoint_productos": "✓ Endpoint de productos respondiendo",
  "log_error_articulos": "✗ Error artículos: {error}",
  "log_error_conexion": "✗ Error de conexión: {error}",
  "log_error_csrf": "✗ Error CSRF: {error}",
  "log_error_productos": "✗ Error productos: {error}",
  "log_error_sesion": "✗ Error de sesión: {error}",
  "login_subtitulo": "Inicia sesión para continuar.",
  "logs_diagnostico": "Logs de Diagnóstico",
  "mantenimiento_texto": "Volveremos en unos minutos.",
  "mantenimiento_titulo": "En Tareas De Mantenimiento, Volveremos Pronto",
  "mas_acciones": "Más acciones",
  "mas_consumido": "Más consumido",
  "mas_opciones": "Más opciones",
  "maximo_n_caracteres": "Máximo {n} caracteres",
  "mensaje_compartir_generico": "Si ese usuario existe, recibirá una invitación para unirse al hogar.",
  "mensaje_reset_generico": "Si esa cuenta existe, recibirás un email con instrucciones para restablecer tu contraseña.",
  "mi_lista": "Mi lista",
  "mi_perfil": "Mi Perfil",
  "mi_stock": "Mi Stock",
  "miembro": "Miembro",
  "miembros_con_acceso": "👥 Miembros con acceso",
  "miembros_lista": "Miembros de la lista",
  "minimo_4_caracteres": "Mínimo 4 caracteres",
  "minimo_8_caracteres": "Mínimo 8 caracteres",
  "minimo_n_caracteres": "Mínimo {n} caracteres",
  "mis_articulos_personalizados": "Mis artículos personalizados",
  "mis_hogares": "Mis hogares",
  "modal_terminos_texto": "Para seguir usando Dreame! necesitas leer y aceptar la versión vigente de los Términos y Condiciones y la Política de Privacidad.",
  "modal_terminos_titulo": "Hemos actualizado nuestros Términos y Condiciones",
  "modo_oscuro": "Modo Oscuro",
  "mostrar_password": "Mostrar contraseña",
  "n_dias": "{n} días",
  "nadie_tiene_acceso": "Nadie más tiene acceso todavía.",
  "nav_compra": "Compra",
  "nav_escanear": "Escanear",
  "nav_gastos": "Gastos",
  "nav_lista_compra": "Lista de la compra",
  "nav_recetas": "Recetas",
  "nav_stock": "Stock",
  "no": "No",
  "no_hay_miembros_compartidos": "No hay miembros compartidos",
  "no_hay_productos": "No hay productos. Pulsa \"+\" para añadir el primero.",
  "no_hay_productos_inventario": "No hay productos en el inventario",
  "no_hay_productos_pendientes_revision": "No hay productos pendientes de revisión.",
  "no_recibiste_codigo": "¿No recibiste el código?",
  "no_se_encontraron_productos": "No se encontraron productos.",
  "no_se_encontraron_usuarios": "No se encontraron usuarios",
  "no_tienes_cuenta": "¿No tienes cuenta?",
  "nombre": "Nombre",
  "nombre_actualizado": "Nombre actualizado correctamente",
  "nombre_completo": "Nombre completo",
  "nombre_e_imagen": "Nombre e imagen",
  "nombre_ingrediente": "Nombre",
  "nombre_lista": "Nombre de la lista",
  "nombre_nuevo_hogar": "Nombre del nuevo hogar",
  "nombre_receta": "Nombre de la receta",
  "nombre_usuario_actualizado": "Nombre de usuario actualizado correctamente",
  "nota_cerrar_sesion_dispositivo": "Se cerrará tu sesión en este dispositivo",
  "nota_eliminar_cuenta_irreversible": "Esta acción es irreversible. Se eliminarán permanentemente todos tus datos.",
  "nota_idioma_completo": "Cambia el idioma de toda la interfaz",
  "nota_opcional": "Nota (opcional)",
  "nota_tema_inmediato": "El cambio de tema se aplica inmediatamente en toda la aplicación",
  "notificaciones_push_descripcion": "Recibe un aviso cuando un producto lleve tiempo sin tocarse, por si ha caducado.",
  "notificaciones_push_titulo": "Notificaciones push",
  "nueva_categoria": "Nueva categoría",
  "nueva_contrasena_opcional": "Nueva contraseña (dejar en blanco para no cambiar)",
  "nueva_lista": "Nueva lista",
  "nueva_receta": "Nueva receta",
  "nuevo_articulo": "Nuevo Artículo",
  "nuevo_badge": "Nuevo",
  "nuevo_gasto": "Nuevo gasto",
  "nuevo_producto": "Nuevo producto",
  "ocr_instrucciones": "Lectura local con OCR (sin conexión a internet). Es orientativa: revisa y corrige los artículos detectados antes de añadirlos al stock.",
  "ocr_local_descripcion": "Si lo activas, las fotos de tickets no se envian a Anthropic (nube); se procesan solo con reconocimiento local, algo menos preciso.",
  "ocr_local_titulo": "Escanear tickets solo en local",
  "ocultar_password": "Ocultar contraseña",
  "ok": "OK",
  "olvidaste_password": "¿Olvidaste tu contraseña?",
  "opcional": "(opcional: si no eliges uno se usa el de la categoría)",
  "orden_alfabetico": "Alfabético (A → Z)",
  "orden_categoria": "Por categoría (agrupado)",
  "orden_manual": "Manual (arrastra para reordenar)",
  "orden_pendientes_primero": "Pendientes primero (sin tachar)",
  "ordenando": "Ordenando",
  "paga_a": "paga a",
  "pagado_por": "Pagado por",
  "pagador": "Pagador",
  "pagar": "Pagar",
  "pagos_sugeridos": "Pagos sugeridos",
  "pais_argentina": "Argentina",
  "pais_chile": "Chile",
  "pais_colombia": "Colombia",
  "pais_espana": "España",
  "pais_mexico": "México",
  "pais_peru": "Perú",
  "participante": "Participante",
  "participantes": "Participantes",
  "password_actual": "Contraseña Actual",
  "password_cambiada_correctamente": "Contraseña cambiada correctamente",
  "password_nueva": "Nueva Contraseña",
  "password_restablecida_ok": "Tu contraseña se ha restablecido correctamente.",
  "pausar": "Pausar",
  "pendiente": "Pendiente",
  "pendientes_contador": "Pendientes",
  "permiso": "Permiso",
  "permiso_actualizado": "Permiso actualizado",
  "permiso_editar": "Permiso de edición",
  "permiso_editar_lectura_escritura": "✏️ Editar (lectura y escritura)",
  "permiso_notificaciones_denegado": "Has bloqueado los permisos de notificaciones en el navegador.",
  "permiso_ver": "Solo ver",
  "permiso_ver_solo_lectura": "👁️ Ver (solo lectura)",
  "personalizar_lista": "Personalizar lista",
  "placeholder_buscar_nombre_categoria": "Buscar por nombre o categoría...",
  "placeholder_codigo": "Código de 6 dígitos",
  "placeholder_confirma_contrasena": "Confirma tu contraseña",
  "placeholder_ej_articulo": "ej: Leche, Pan, Detergente...",
  "placeholder_ej_producto": "ej: Leche, Arroz, Detergente...",
  "placeholder_email_ejemplo": "usuario@example.com",
  "placeholder_nombre_hogar": "ej: Casa, Piso compartido...",
  "placeholder_nuevo_nombre": "Tu nombre",
  "placeholder_nuevo_nombre_usuario": "Nuevo nombre de usuario",
  "placeholder_password_confirmacion": "Confirmar contraseña",
  "placeholder_password_nueva": "Contraseña nueva",
  "placeholder_telefono": "Teléfono (opcional, ej: +34 123 45 67 89)",
  "placeholder_tu_contrasena": "Tu contraseña",
  "placeholder_tu_email": "tu@email.com",
  "placeholder_tu_nombre": "Tu nombre",
  "placeholder_tu_password_actual": "Tu contraseña actual",
  "placeholder_tu_usuario": "Tu usuario",
  "placeholder_usuario_o_email": "Nombre de usuario o email (min. 2 letras)",
  "pocas_unidades": "¡Pocas unidades!",
  "por_defecto_localhost": "http://localhost:5000 (por defecto)",
  "precio": "Precio",
  "precio_anómalo": "Precio anómalo",
  "precio_ha_bajado": "El precio ha bajado",
  "precio_ha_subido": "El precio ha subido",
  "presupuesto_consumido": "consumido",
  "presupuesto_mensual": "Presupuesto mensual",
  "problemas_conectividad_titulo": "¿Problemas de conectividad?",
  "procesando": "Procesando...",
  "procesar_ticket": "Procesando ticket...",
  "producto_bajo_stock_minimo_uno": "producto bajo de stock mínimo",
  "producto_bajo_stock_minimo_varios": "productos bajos de stock mínimo",
  "producto_plural": "productos",
  "producto_singular": "producto",
  "productos": "Productos",
  "productos_check": "Productos (/api/productos)",
  "productos_detectados_contador": "{n} producto(s) detectado(s)",
  "promocion_detectada": "Promoción detectada",
  "propietario": "PROPIETARIO",
  "propietario_rol": "Propietario",
  "propios": "Propios",
  "puede_comprar": "Puede marcar comprado",
  "puede_editar": "Puede editar",
  "push_presupuesto_superado_cuerpo": "Este mes se ha superado el presupuesto fijado para {nombre}.",
  "push_presupuesto_superado_titulo": "Presupuesto superado",
  "quitar": "Quitar",
  "reanudar": "Reanudar",
  "rechazar": "Rechazar",
  "recibo": "Recibo",
  "recuadros": "Recuadros",
  "recurso_articulo": "Artículo",
  "recurso_articulo_personalizado": "Artículo personalizado",
  "recurso_categoria": "Categoría",
  "recurso_gasto": "Gasto",
  "recurso_gasto_recurrente": "Gasto recurrente",
  "recurso_hogar": "Lista",
  "recurso_invitacion": "Invitación",
  "recurso_liquidacion": "Liquidación",
  "recurso_producto": "Producto",
  "recurso_receta": "Receta",
  "recurso_recibo": "Recibo",
  "redirigiendo_a_tu_hogar": "Redirigiendo a tu hogar...",
  "reenviando": "Reenviando...",
  "reenviar_codigo": "Reenviar código",
  "region": "Región",
  "region_e_idioma": "Región e idioma",
  "registrar_pago": "Registrar pago",
  "registro": "Registro",
  "registro_subtitulo": "Crea tu cuenta para empezar.",
  "reintentar_diagnostico": "Reintentar Diagnóstico",
  "renombrar": "Renombrar",
  "reparto_cuadra": "El reparto cuadra",
  "reparto_no_cuadra": "El reparto no cuadra con el importe total",
  "requiere_sesion_esperado": "Requiere sesión (esperado sin login)",
  "respondiendo_correctamente": "Respondiendo correctamente",
  "respuesta_inesperada": "Respuesta inesperada ({status})",
  "restableciendo_password": "Restableciendo tu contraseña...",
  "restaurar": "Restaurar",
  "resumen": "Resumen",
  "revisar": "Revisar",
  "revisar_caducidad": "⏰ Revisar caducidad",
  "saldar": "Saldar",
  "saldo_neto": "Saldo",
  "salir": "Salir",
  "salir_lista": "Salir de esta lista",
  "se_divide": "Se divide",
  "seccion_apariencia": "Apariencia",
  "seccion_cuenta": "Cuenta",
  "seccion_preferencias_listas": "Preferencias de Listas",
  "selecciona_hogar_texto": "Necesitas seleccionar un hogar para ver el stock y la lista de la compra",
  "selecciona_un_usuario": "Selecciona un usuario",
  "seleccionar_icono": "Seleccionar icono",
  "seleccionar_todos": "Seleccionar todos",
  "separador_o": "o",
  "sesion_check": "Sesión (/api/auth/estado)",
  "sesion_iniciada_como": "Sesión iniciada como \"{usuario}\"",
  "sesion_no_iniciada": "Sin sesión iniciada (normal si no has hecho login)",
  "sesiones_cerradas_confirmacion": "Se ha cerrado la sesión en tus otros dispositivos.",
  "si": "Sí",
  "si_cerrar_sesion": "Sí, cerrar sesión",
  "si_eliminar_cuenta": "Sí, eliminar cuenta",
  "sin_agrupar": "Sin agrupar",
  "sin_categoria": "Sin categoría",
  "sin_categorias_aun": "Todavía no hay categorías propias.",
  "sin_coincidencias_catalogo": "Sin coincidencias, escribe el nombre abajo para crear uno nuevo",
  "sin_conexion": "Sin conexión",
  "sin_conexion_aviso": "Sin conexion. Mostrando la ultima version guardada.",
  "sin_consumo_registrado": "Sin consumo registrado en este periodo (baja la cantidad de algún producto en Stock para que aparezca aquí).",
  "sin_datos_estadisticas": "No hay datos suficientes para mostrar estadísticas todavía.",
  "sin_gastos_aun": "Todavía no hay gastos registrados.",
  "sin_gastos_descripcion": "Apunta el primer gasto compartido y calcularemos quién debe a quién.",
  "sin_gastos_titulo": "Aún no hay gastos",
  "sin_historial_precios": "Aun no hay precios registrados para este producto. Se registran al confirmar un ticket escaneado que lo incluya.",
  "sin_hogares_crea_uno_nuevo": "Sin hogares aún. Crea uno nuevo.",
  "sin_iconos_coincidentes": "Ningún icono coincide con esa búsqueda.",
  "sin_logs_aun": "Sin logs aún...",
  "sin_match": "Sin match",
  "sin_presupuesto": "Sin presupuesto fijado",
  "sin_recetas_aun": "Aún no tienes ninguna receta. Crea la primera con sus ingredientes.",
  "sin_resultados": "Sin resultados",
  "sin_resultados_filtro": "Ningún gasto coincide con los filtros aplicados.",
  "sin_resultados_para": "Sin resultados para",
  "stock": "📦 Stock",
  "stock_bajo": "Stock bajo",
  "stock_minimo": "Stock mínimo",
  "subir_archivo_boton": "Subir archivo",
  "subtitulo_ajustes": "Personaliza tu experiencia",
  "subtitulo_app": "Inventario del Hogar",
  "subtitulo_escanear_ticket": "Haz una foto del ticket de compra y añade los productos al stock automáticamente",
  "subtitulo_historial": "Consumo de tu lista activa y catálogo de artículos aprendidos",
  "subtitulo_login": "Accede a tu inventario y listas",
  "subtitulo_mis_hogares": "El hogar \"activo\" es el que ves en Stock y en la Lista de la Compra",
  "subtitulo_registro": "Regístrate para empezar",
  "subtitulo_stock": "Gestiona tu inventario del hogar",
  "subtitulo_verificacion_codigo": "Te hemos enviado un código a tu email. Introdúcelo para continuar.",
  "sugerencias": "Sugerencias",
  "te_deben_total": "Te deben en total",
  "teclado_virtual": "Teclado virtual propio",
  "teclado_virtual_ayuda": "Si usas un lector de pantalla, desactiva esta opción.",
  "tema": "Tema",
  "tema_claro": "Claro",
  "tema_oscuro": "Oscuro",
  "tema_sistema": "Como el dispositivo",
  "ticket": "Ticket",
  "ticket_detectando": "Detectando artículos y cantidades",
  "ticket_importado_resumen": "Ticket importado: {creados} producto(s) nuevo(s), {actualizados} actualizado(s).",
  "ticket_paso_foto": "Foto",
  "ticket_paso_revision": "Revisión",
  "ticket_procesado_local": "JPG, PNG · se procesa en tu dispositivo",
  "tipo": "Tipo",
  "titulo_eventos_seguridad": "Actividad de tu cuenta",
  "titulo_login": "Inicia sesión",
  "titulo_recuperar_password": "Recuperar contraseña",
  "titulo_registro": "Crea tu cuenta",
  "titulo_restablecer_password": "Restablecer contraseña",
  "titulo_verificacion_codigo": "Verificación en dos pasos",
  "titulo_vista_grid": "Vista de grid",
  "titulo_vista_lista": "Vista de lista",
  "titulo_vista_recuadros": "Vista de recuadros",
  "toca_para_foto": "Toca para hacer una foto o elegir una imagen del ticket.",
  "todas": "Todas",
  "todas_las_categorias": "Todas las categorías",
  "todo_en_orden_sin_bajo_minimo": "¡Todo en orden! No hay productos bajo el mínimo.",
  "todos_los_miembros": "Todos los miembros",
  "token_csrf_check": "Token CSRF (/api/csrf-token)",
  "token_no_obtenido": "No se obtuvo el token",
  "token_obtenido": "Token obtenido correctamente",
  "total_mes": "Este mes",
  "tu_balance": "Tu balance",
  "tu_hogar": "Tu hogar",
  "tu_parte": "Tu parte",
  "tu_suffix": "(tú)",
  "tus_hogares": "Tus hogares",
  "ud": "ud",
  "unidad": "Unidad",
  "usar_categoria": "Usar el de la categoría",
  "usar_este_hogar": "Usar este hogar",
  "usuario": "Usuario",
  "ver": "Ver",
  "ver_detalle_gasto": "Ver detalle del gasto",
  "ver_historial_precios": "Ver historial de precios",
  "ver_productos_consumidos": "Ver los productos más consumidos y el catálogo aprendido",
  "ver_recibo": "Ver recibo",
  "ver_stock": "Ver stock",
  "verificacion_email_enviada": "Te hemos enviado un enlace de verificación a tu email.",
  "verificando_email": "Verificando tu email...",
  "vista_lista": "Lista",
  "vista_lista_compra_label": "Vista de la lista de compra",
  "volver": "← Volver",
  "volver_a_login": "Volver a login",
  "vs_mes_anterior": "vs. mes anterior",
  "whatsapp_mensaje_compartir": "Hola! Te quiero compartir mi lista de compra \"{nombre}\" en Dreame! (aplicacion de listas compartidas).\n\nPuedes verla y actualizarla en tiempo real. Únete aquí:\n{enlace}",
  "whatsapp_mensaje_compartir_hogar": "Hola! Quiero compartir mi hogar \"{nombre}\" contigo. 📱\n\n{enlace}",
  "ya_activo": "Ya activo",
  "ya_tienes_cuenta": "¿Ya tienes cuenta?",
  "zona_riesgo": "Zona de Riesgo",
  "éxito": "Éxito"
}

export default TRADUCCIONES_BASE
